using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

Byte[] Utf8Bom = [0xEF, 0xBB, 0xBF];
Byte[] Head = """
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by TypeInfoGenerator in KNSoft.SMBIOS project
//     https://github.com/KNSoft/KNSoft.SMBIOS
//     Do not change this file manually
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "SMBIOS.h"
#include "SMBIOS.TypeInfo.inl"


"""u8.ToArray();

Output.Write(Utf8Bom);
Output.Write(Head);

static String AddEnumType(String EnumName)
{
    if (Enums.TryGetValue(EnumName, out var EnumTypeName))
    {
        return EnumTypeName;
    }

    for (UInt32 i = 1; i < Data.Length; i++)
    {
        if (Data[i].Trim().StartsWith("#define " + EnumName + '_'))
        {
            EnumTypeName = String.Empty;
            Output.Write("__declspec(selectany)\r\nSMBIOS_FIELD_ENUM "u8.ToArray());
            String[] Words = EnumName.Split('_');
            foreach (String Word in Words)
            {
                EnumTypeName += Char.ToUpper(Word[0]) + Word[1..Word.Length].ToLower();
            }
            EnumTypeName += "Enum";
            Output.Write(Encoding.UTF8.GetBytes(EnumTypeName));
            Output.Write("[] = {\r\n"u8.ToArray());
            do
            {
                Match Match = RxEnumDefine().Match(Data[i].Trim());
                if (!Match.Success || Match.Groups.Count != 3)
                {
                    Output.Write("};\r\n\r\n"u8.ToArray());
                    Enums.Add(EnumName, EnumTypeName);
                    return EnumTypeName;
                }
                Output.Write(Encoding.UTF8.GetBytes(
                    "    { u8\"" +
                    Match.Groups[2].Value + "\", " +
                    Match.Groups[1].Value + " },\r\n"));
                i++;
            } while (i < Data.Length);
        }
    }

    return String.Empty;
}

for (UInt32 i = 1; i < Data.Length; i++)
{
    UInt32 j;
    Int32 Colon;
    Match Match;
    String TypeNumber;

    /* Find type (line [j..i]) */
    Match = RxType().Match(Data[i]);
    if (!Match.Success || Match.Groups.Count != 5 ||
        Match.Groups[1].Value != Match.Groups[2].Value ||
        Match.Groups[3].Value != Match.Groups[4].Value)
    {
        continue;
    }
    for (j = i - 1; j > 0; j--)
    {
        if (Data[j] == "typedef struct _SMBIOS_" + Match.Groups[1].Value)
        {
            break;
        }
    }
    if (Data[j + 1] != "{" || Data[j + 2] != "    SMBIOS_HEADER Header;")
    {
        continue;
    }
    j += 2;
    TypeNumber = Match.Groups[3].Value;

    /* Process each field */
    List<String> Fields = [];
    String Parent = String.Empty, ParentComment = String.Empty;
    UInt16 ParentBits = 0;
    Boolean InCommentBlock = false;
    for (UInt32 k = i - 1; k > j; k--)
    {
        String Field, Comment, Name, Count = String.Empty, EnumName = String.Empty, TypeInfo;
        Field = Data[k].Trim();

        /* Skip comments */
        if (Field == "*/")
        {
            InCommentBlock = true;
            continue;
        } else if (Field.StartsWith("/*"))
        {
            InCommentBlock = false;
            continue;
        } else if (InCommentBlock)
        {
            continue;
        }

        /* Skip version control */
        if (Field.StartsWith("#if SMBIOS_VERSION ") ||
            Field.StartsWith("#else") ||
            Field.StartsWith("#endif // SMBIOS_VERSION "))
        {
            continue;
        }

        /* Inside structures */
        if (Field == "union")
        {
            Parent = String.Empty;
            ParentComment = String.Empty;
            ParentBits = 0;
            continue;
        }
        if (Field == "struct" || Field == "{" || Field == "};")
        {
            continue;
        }
        if (Field[0] == '}')
        {
            Parent = Field[1..Field.IndexOf(';')].Trim();
            ParentComment = Field[(Field.IndexOf("// ") + 3)..Field.Length];
            continue;
        }

        /* Skip SAL */
        if (Field.StartsWith("_Field_size"))
        {
            Field = Field[(Field.IndexOf(')') + 2)..Field.Length];
        }

        /* Resolve each part of field */
        Match = RxField().Match(Field);
        if (!Match.Success || Match.Groups.Count != 4)
        {
            throw new Exception("Cannot resolve line " + k.ToString() + ": " + Field);
        }

        Name = Match.Groups[2].Value;
        if (Name.EndsWith(']'))
        {
            Count = Name[(Name.IndexOf('[') + 1)..Name.IndexOf(']')];
            if (String.IsNullOrEmpty(Count))
            {
                continue;
            }
            Colon = -1;
        } else
        {
            Count = String.Empty;
            Colon = Name.IndexOf(':');
        }
        Comment = Match.Groups[3].Value.Trim();
        if (Comment.StartsWith("// "))
        {
            Comment = Comment[3..Comment.Length];
            Match EnumMatch = RxEnumField().Match(Comment);
            if (EnumMatch.Success && EnumMatch.Groups.Count == 3)
            {
                Comment = EnumMatch.Groups[1].Value;
                EnumName = EnumMatch.Groups[2].Value;
            }
        }
        if (Colon == -1)
        {
            if (String.IsNullOrEmpty(EnumName))
            {
                if (Match.Groups[2].Value == "Value" && Data[k - 2].Trim() == "union")
                {
                    TypeInfo =
                        "SMBIOS_DEFINE_FIELD_UINT(" +
                        TypeNumber + ", \"" + ParentComment + "\", " + Parent +
                        ".Value),";
                } else if (Match.Groups[1].Value == "BYTE" || Match.Groups[1].Value == "WORD" ||
                    Match.Groups[1].Value == "DWORD" || Match.Groups[1].Value == "QWORD")
                {
                    TypeInfo =
                        "SMBIOS_DEFINE_FIELD_UINT(" +
                        TypeNumber + ", \"" + Comment + "\", " + Match.Groups[2].Value +
                        "),";
                } else if (Match.Groups[1].Value == "UCHAR")
                {
                    TypeInfo =
                        "SMBIOS_DEFINE_FIELD_STRING(" +
                        TypeNumber + ", \"" + Comment + "\", " + Match.Groups[2].Value +
                        "),";
                } else if (Match.Groups[1].Value == "SMBIOS_UUID")
                {
                    TypeInfo =
                        "SMBIOS_DEFINE_FIELD(" +
                        TypeNumber + ", \"" + Comment + "\", " + Match.Groups[2].Value +
                        ", SmbiosDataTypeUuid),";
                } else
                {
                    Console.WriteLine("Cannot resolve line " + k.ToString() + ": " + Field);
                    continue;
                }
            } else
            {
                TypeInfo =
                        "SMBIOS_DEFINE_FIELD_ENUM(" +
                        TypeNumber + ", \"" + Comment + "\", " +
                        Match.Groups[2].Value + ", " + AddEnumType(EnumName) + "),";
            }
        } else
        {
            if (ParentBits == 0)
            {
                ParentBits = Match.Groups[1].Value switch
                {
                    "BYTE" => 8,
                    "WORD" => 16,
                    "DWORD" => 32,
                    "QWORD" => 64,
                    _ => throw new ArgumentException("Unrecognized 'Type' of bit field: " + Match.Groups[1].Value)
                };
            }
            Name = Comment[(Comment.IndexOf(' ') + 1)..Comment.Length].Replace("\"", "\\\"");
            UInt16 BitSize = UInt16.Parse(Match.Groups[2].Value[(Colon + 1)..Match.Groups[2].Value.Length].Trim());
            ParentBits -= BitSize;
            if (BitSize == 1)
            {
                TypeInfo =
                    "SMBIOS_DEFINE_FIELD_BIT(\"" +
                    Name + "\", " + ParentBits.ToString() +
                    "),";
            } else
            {
                if (String.IsNullOrEmpty(EnumName))
                {
                    TypeInfo =
                        "SMBIOS_DEFINE_BIT_FIELD(\"" +
                        Name + "\", " + ParentBits.ToString() + ", " + BitSize.ToString() +
                        ", SmbiosDataTypeUInt),";
                } else
                {
                    TypeInfo =
                        "SMBIOS_DEFINE_BIT_FIELD(\"" +
                        Name + "\", " + ParentBits.ToString() + ", " + BitSize.ToString() +
                        ", SmbiosDataTypeEnum, SMBIOS_FIELD_ENUM_VALUES(" + AddEnumType(EnumName) +
                        ")),";
                }
            }
        }
        Fields.Add(TypeInfo);
    }

    Output.Write("__declspec(selectany)\r\nSMBIOS_FIELD_TYPE_INFO SmbiosType"u8.ToArray());
    Output.Write(Encoding.UTF8.GetBytes(TypeNumber));
    Output.Write("FieldInfo[] = {\r\n"u8.ToArray());
    if (Fields.Count > 0)
    {
        for (Int32 k = Fields.Count - 1; k >= 0; k--)
        {
            Output.Write("    "u8.ToArray());
            Output.Write(Encoding.UTF8.GetBytes(Fields[k]));
            Output.Write("\r\n"u8.ToArray());
        }
    }
    Output.Write("};\r\n\r\n"u8.ToArray());
}

Output.Dispose();

partial class Program
{
    [GeneratedRegex(@"\} SMBIOS_(\w+), \*PSMBIOS_(\w+), SMBIOS_TYPE_(\d+), \*PSMBIOS_TYPE_(\d+);", RegexOptions.Compiled)]
    private static partial Regex RxType();

    [GeneratedRegex(@"(\w+) (.+);(.*)", RegexOptions.Compiled)]
    private static partial Regex RxField();

    [GeneratedRegex(@"(.+), (SMBIOS_\w+)_\*", RegexOptions.Compiled)]
    private static partial Regex RxEnumField();

    [GeneratedRegex(@"#define (SMBIOS_\w+) +\(\S+\) // (.+)", RegexOptions.Compiled)]
    private static partial Regex RxEnumDefine();

    private static readonly String[] Data = File.ReadAllLines("../../../../SMBIOS.h");
    private static readonly FileStream Output = File.Create("../../../../TypeInfo.h");
    private static readonly Dictionary<String, String> Enums = [];
}
