#pragma once

#include "SMBIOS.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

typedef enum _SMBIOS_DATA_TYPE
{
    SmbiosDataTypeOther,
    SmbiosDataTypeString,
    SmbiosDataTypeUInt,
    SmbiosDataTypeBit,
    SmbiosDataTypeEnum,
    SmbiosDataTypeUuid,
} SMBIOS_DATA_TYPE, *PSMBIOS_DATA_TYPE;

typedef struct _SMBIOS_FIELD_ENUM
{
    const char* Name;
    QWORD Value;
} SMBIOS_FIELD_ENUM, *PSMBIOS_FIELD_ENUM;

typedef struct _SMBIOS_FIELD_TYPE_INFO
{
    const char* Name;
    BYTE IsBitField;
    WORD Offset;
    BYTE Size;
    SMBIOS_DATA_TYPE Type;
    union
    {
        struct
        {
            WORD Count;
            _Field_size_(Count) PSMBIOS_FIELD_ENUM Values;
        } Enum;
    } AdditionalInfo;
} SMBIOS_FIELD_TYPE_INFO, *PSMBIOS_FIELD_TYPE_INFO;

typedef struct _SMBIOS_TYPE_INFO
{
    BYTE Type;          // Type number in SMBIOS spec.
    const char* Name;   // Type name in SMBIOS spec.
    WORD FieldCount;    // Number of Fields
    _Field_size_(FieldCount) PSMBIOS_FIELD_TYPE_INFO Fields;  // Field information in type structure
} SMBIOS_TYPE_INFO, *PSMBIOS_TYPE_INFO;

#define SMBIOS_DEFINE_FIELD(Type, Name, Field, FieldType, ...) { Name, false, (WORD)offsetof(SMBIOS_TYPE_##Type, Field), (BYTE)sizeof(((SMBIOS_TYPE_##Type*)0)->Field), FieldType, __VA_ARGS__ }
#define SMBIOS_DEFINE_BIT_FIELD(Name, BitOffset, BitSize, FieldType, ...) { Name, true, BitOffset, BitSize, FieldType, __VA_ARGS__ }
#define SMBIOS_FIELD_ENUM_VALUES(EnumName) { _countof(EnumName), EnumName }

#define SMBIOS_DEFINE_FIELD_STRING(Type, Name, Field) SMBIOS_DEFINE_FIELD(Type, Name, Field, SmbiosDataTypeString)
#define SMBIOS_DEFINE_FIELD_UINT(Type, Name, Field) SMBIOS_DEFINE_FIELD(Type, Name, Field, SmbiosDataTypeUInt)
#define SMBIOS_DEFINE_FIELD_ENUM(Type, Name, Field, EnumName) SMBIOS_DEFINE_FIELD(Type, Name, Field, SmbiosDataTypeEnum, SMBIOS_FIELD_ENUM_VALUES(EnumName))
#define SMBIOS_DEFINE_FIELD_BIT(Name, BitOffset) SMBIOS_DEFINE_BIT_FIELD(Name, BitOffset, 1, SmbiosDataTypeBit)

#define SMBIOS_DEFINE_TYPE(Type, Name) { Type, Name, _countof(SmbiosType##Type##FieldInfo), SmbiosType##Type##FieldInfo }

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosMemoryErrorTypeEnum[] = {
    { "Other", SMBIOS_MEMORY_ERROR_TYPE_OTHER },
    { "Unknown", SMBIOS_MEMORY_ERROR_TYPE_UNKNOWN },
    { "OK", SMBIOS_MEMORY_ERROR_TYPE_OK },
    { "Bad read", SMBIOS_MEMORY_ERROR_TYPE_BAD_READ },
    { "Parity error", SMBIOS_MEMORY_ERROR_TYPE_PARITY },
    { "Single-bit error", SMBIOS_MEMORY_ERROR_TYPE_SINGLE_BIT },
    { "Double-bit error", SMBIOS_MEMORY_ERROR_TYPE_DOUBLE_BIT },
    { "Multi-bit error", SMBIOS_MEMORY_ERROR_TYPE_MULTI_BIT },
    { "Nibble error", SMBIOS_MEMORY_ERROR_TYPE_NIBBLE },
    { "Checksum error", SMBIOS_MEMORY_ERROR_TYPE_CHECKSUM },
    { "CRC error", SMBIOS_MEMORY_ERROR_TYPE_CRC },
    { "Corrected single-bit error", SMBIOS_MEMORY_ERROR_TYPE_CORRECTED_SINGLE_BIT },
    { "Corrected error", SMBIOS_MEMORY_ERROR_TYPE_CORRECTED },
    { "Uncorrectable error", SMBIOS_MEMORY_ERROR_TYPE_UNCORRECTABLE },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosMemoryErrorGranularityEnum[] = {
    { "Other", SMBIOS_MEMORY_ERROR_GRANULARITY_OTHER },
    { "Unknown", SMBIOS_MEMORY_ERROR_GRANULARITY_UNKNOWN },
    { "Device level", SMBIOS_MEMORY_ERROR_GRANULARITY_DEVICE_LEVEL },
    { "Memory partition level", SMBIOS_MEMORY_ERROR_GRANULARITY_MEMORY_PARTITION_LEVEL },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosMemoryErrorOperationEnum[] = {
    { "Other", SMBIOS_MEMORY_ERROR_OPERATION_OTHER },
    { "Unknown", SMBIOS_MEMORY_ERROR_OPERATION_UNKNOWN },
    { "Read", SMBIOS_MEMORY_ERROR_OPERATION_READ },
    { "Write", SMBIOS_MEMORY_ERROR_OPERATION_WRITE },
    { "Partial write", SMBIOS_MEMORY_ERROR_OPERATION_PARTIAL_WRITE },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType0ExtendedROMSizeUnitEnum[] = {
    { "MB", SMBIOS_PLATFORM_FIRMWARE_EXTENDEDROMSIZE_UNIT_MB },
    { "GB", SMBIOS_PLATFORM_FIRMWARE_EXTENDEDROMSIZE_UNIT_GB },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType0FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(0, "Vendor", Vendor),
    SMBIOS_DEFINE_FIELD_STRING(0, "Firmware Version", Version),
    SMBIOS_DEFINE_FIELD_UINT(0, "BIOS Starting Address Segment", BIOSStartingAddressSegment),
    SMBIOS_DEFINE_FIELD_STRING(0, "Firmware Release Date", ReleaseDate),
    SMBIOS_DEFINE_FIELD_UINT(0, "Firmware ROM Size", ROMSize),
    SMBIOS_DEFINE_FIELD_UINT(0, "Firmware Characteristics", Characteristics),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 0),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 1),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 2),
    SMBIOS_DEFINE_FIELD_BIT("Firmware Characteristics are not supported", 3),
    SMBIOS_DEFINE_FIELD_BIT("ISA is supported", 4),
    SMBIOS_DEFINE_FIELD_BIT("MCA is supported", 5),
    SMBIOS_DEFINE_FIELD_BIT("EISA is supported", 6),
    SMBIOS_DEFINE_FIELD_BIT("PCI is supported", 7),
    SMBIOS_DEFINE_FIELD_BIT("PC card (PCMCIA) is supported", 8),
    SMBIOS_DEFINE_FIELD_BIT("Plug and Play is supported", 9),
    SMBIOS_DEFINE_FIELD_BIT("APM is supported", 10),
    SMBIOS_DEFINE_FIELD_BIT("Firmware is upgradeable (Flash)", 11),
    SMBIOS_DEFINE_FIELD_BIT("Firmware shadowing is allowed", 12),
    SMBIOS_DEFINE_FIELD_BIT("VL-VESA is supported", 13),
    SMBIOS_DEFINE_FIELD_BIT("ESCD support is available", 14),
    SMBIOS_DEFINE_FIELD_BIT("Boot from CD is supported", 15),
    SMBIOS_DEFINE_FIELD_BIT("Selectable boot is supported", 16),
    SMBIOS_DEFINE_FIELD_BIT("Firmware ROM is socketed (e.g., PLCC or SOP socket)", 17),
    SMBIOS_DEFINE_FIELD_BIT("Boot from PC card (PCMCIA) is supported", 18),
    SMBIOS_DEFINE_FIELD_BIT("EDD specification is supported", 19),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — Japanese floppy for NEC 9800 1.2 MB (3.5\", 1K bytes/sector, 360 RPM) is supported", 20),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — Japanese floppy for Toshiba 1.2 MB (3.5\", 360 RPM) is supported", 21),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — 5.25\" / 360 KB floppy services are supported", 22),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — 5.25\" / 1.2 MB floppy services are supported", 23),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — 3.5\" / 720 KB floppy services are supported", 24),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — 3.5\" / 2.88 MB floppy services are supported", 25),
    SMBIOS_DEFINE_FIELD_BIT("Int 5h, print screen service is supported", 26),
    SMBIOS_DEFINE_FIELD_BIT("Int 9h, 8042 keyboard services are supported", 27),
    SMBIOS_DEFINE_FIELD_BIT("Int 14h, serial services are supported", 28),
    SMBIOS_DEFINE_FIELD_BIT("Int 17h, printer services are supported", 29),
    SMBIOS_DEFINE_FIELD_BIT("Int 10h, CGA/Mono Video Services are supported", 30),
    SMBIOS_DEFINE_FIELD_BIT("NEC PC-98", 31),
    SMBIOS_DEFINE_FIELD_UINT(0, "Firmware Characteristics Extension Byte 1", CharacteristicsExtensionByte1),
    SMBIOS_DEFINE_FIELD_BIT("ACPI is supported", 0),
    SMBIOS_DEFINE_FIELD_BIT("USB Legacy is supported", 1),
    SMBIOS_DEFINE_FIELD_BIT("AGP is supported", 2),
    SMBIOS_DEFINE_FIELD_BIT("I2O boot is supported", 3),
    SMBIOS_DEFINE_FIELD_BIT("LS-120 SuperDisk boot is supported", 4),
    SMBIOS_DEFINE_FIELD_BIT("ATAPI ZIP drive boot is supported", 5),
    SMBIOS_DEFINE_FIELD_BIT("1394 boot is supported", 6),
    SMBIOS_DEFINE_FIELD_BIT("Smart battery is supported", 7),
    SMBIOS_DEFINE_FIELD_UINT(0, "Firmware Characteristics Extension Byte 2", CharacteristicsExtensionByte2),
    SMBIOS_DEFINE_FIELD_BIT("BIOS Boot Specification is supported", 0),
    SMBIOS_DEFINE_FIELD_BIT("Function key-initiated network service boot is supported", 1),
    SMBIOS_DEFINE_FIELD_BIT("Enable targeted content distribution", 2),
    SMBIOS_DEFINE_FIELD_BIT("UEFI Specification is supported", 3),
    SMBIOS_DEFINE_FIELD_BIT("SMBIOS table describes a virtual machine", 4),
    SMBIOS_DEFINE_FIELD_BIT("Manufacturing mode is supported", 5),
    SMBIOS_DEFINE_FIELD_BIT("Manufacturing mode is enabled", 6),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 7),
    SMBIOS_DEFINE_FIELD_UINT(0, "Platform Firmware Major Release", MajorRelease),
    SMBIOS_DEFINE_FIELD_UINT(0, "Platform Firmware Minor Release", MinorRelease),
    SMBIOS_DEFINE_FIELD_UINT(0, "Embedded Controller Firmware Major Release", ECFirmwareMajorRelease),
    SMBIOS_DEFINE_FIELD_UINT(0, "Embedded Controller Firmware Minor Release", ECFirmwareMinorRelease),
    SMBIOS_DEFINE_FIELD_UINT(0, "Extended Firmware ROM Size", ExtendedROMSize.Value),
    SMBIOS_DEFINE_BIT_FIELD("Size", 0, 14, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Unit", 14, 2, SmbiosDataTypeEnum, SMBIOS_FIELD_ENUM_VALUES(SmbiosType0ExtendedROMSizeUnitEnum)),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType1WakeUpTypeEnum[] = {
    { "Reserved", SMBIOS_SYSTEM_WAKEUPTYPE_RESERVED },
    { "Other", SMBIOS_SYSTEM_WAKEUPTYPE_OTHER },
    { "Unknown", SMBIOS_SYSTEM_WAKEUPTYPE_UNKNOW },
    { "APM Timer", SMBIOS_SYSTEM_WAKEUPTYPE_APM_TIMER },
    { "Modem Ring", SMBIOS_SYSTEM_WAKEUPTYPE_MODEM_RING },
    { "LAN Remote", SMBIOS_SYSTEM_WAKEUPTYPE_LAN_REMOTE },
    { "Power Switch", SMBIOS_SYSTEM_WAKEUPTYPE_POWER_SWITCH },
    { "PCI PME#", SMBIOS_SYSTEM_WAKEUPTYPE_PCI_PME },
    { "AC Power Restored", SMBIOS_SYSTEM_WAKEUPTYPE_AC_POWER_RESTORED },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType1FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(1, "Manufacturer", Manufacturer),
    SMBIOS_DEFINE_FIELD_STRING(1, "Product Name", ProductName),
    SMBIOS_DEFINE_FIELD_STRING(1, "Version", Version),
    SMBIOS_DEFINE_FIELD_STRING(1, "Serial Number", SerialNumber),
    SMBIOS_DEFINE_FIELD(1, "UUID", UUID, SmbiosDataTypeUuid),
    SMBIOS_DEFINE_FIELD_ENUM(1, "Wake-up Type", WakeUpType, SmbiosType1WakeUpTypeEnum),
    SMBIOS_DEFINE_FIELD_STRING(1, "SKU Number", SKUNumber),
    SMBIOS_DEFINE_FIELD_STRING(1, "Family", Family),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType2BoardTypeEnum[] = {
    { "Unknown", SMBIOS_BASEBOARD_TYPE_UNKNOWN },
    { "Other", SMBIOS_BASEBOARD_TYPE_OTHER },
    { "Server Blade", SMBIOS_BASEBOARD_TYPE_SERVER_BLADE },
    { "Connectivity Switch", SMBIOS_BASEBOARD_TYPE_CONNECTIVITY_SWITCH },
    { "System Management Module", SMBIOS_BASEBOARD_TYPE_SYSTEM_MANAGEMENT_MODULE },
    { "Processor Module", SMBIOS_BASEBOARD_TYPE_PROCESSOR_MODULE },
    { "I/O Module", SMBIOS_BASEBOARD_TYPE_IO_MODULE },
    { "Memory Module", SMBIOS_BASEBOARD_TYPE_MEMORY_MODULE },
    { "Daughter board", SMBIOS_BASEBOARD_TYPE_DAUGHTER_BOARD },
    { "Motherboard (includes processor, memory, and I/O)", SMBIOS_BASEBOARD_TYPE_MOTHERBOARD },
    { "Processor/Memory Module", SMBIOS_BASEBOARD_TYPE_PROCESSOR_MEMORY_MODULE },
    { "Processor/IO Module", SMBIOS_BASEBOARD_TYPE_PROCESSOR_IO_MODULE },
    { "Interconnect board", SMBIOS_BASEBOARD_TYPE_INTERCONNECT_BOARD },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType2FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(2, "Manufacturer", Manufacturer),
    SMBIOS_DEFINE_FIELD_STRING(2, "Product", Product),
    SMBIOS_DEFINE_FIELD_STRING(2, "Version", Version),
    SMBIOS_DEFINE_FIELD_STRING(2, "Serial Number", SerialNumber),
    SMBIOS_DEFINE_FIELD_STRING(2, "Asset Tag", AssetTag),
    SMBIOS_DEFINE_FIELD(2, "Feature Flags", FeatureFlags, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("The board is a hosting board (for example, a motherboard)", 0),
    SMBIOS_DEFINE_FIELD_BIT("The board requires at least one daughter board or auxiliary card to function properly", 1),
    SMBIOS_DEFINE_FIELD_BIT("The board is removable", 2),
    SMBIOS_DEFINE_FIELD_BIT("The board is replaceable", 3),
    SMBIOS_DEFINE_FIELD_BIT("The board is s hot swappable", 4),
    SMBIOS_DEFINE_FIELD_STRING(2, "Location in Chassis", LocationInChassis),
    SMBIOS_DEFINE_FIELD(2, "Chassis Handle", ChassisHandle, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_ENUM(2, "Board Type", BoardType, SmbiosType2BoardTypeEnum),
    SMBIOS_DEFINE_FIELD(2, "Number of Contained Object Handles", NumberOfContainedObjectHandles, SmbiosDataTypeUInt),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType3TypeEnum[] = {
    { "Other", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_OTHER },
    { "Unknown", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_UNKNOWN },
    { "Desktop", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_DESKTOP },
    { "Low Profile Desktop", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_LOW_PROFILE_DESKTOP },
    { "Pizza Box", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_PIZZA_BOX },
    { "Mini Tower", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_MINI_TOWER },
    { "Tower", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_TOWER },
    { "Portable", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_PORTABLE },
    { "Laptop", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_LAPTOP },
    { "Notebook", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_NOTEBOOK },
    { "Hand Held", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_HAND_HELD },
    { "Docking Station", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_DOCKING_STATION },
    { "All in One", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_ALL_IN_ONE },
    { "Sub Notebook", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_SUB_NOTEBOOK },
    { "Space-saving", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_SPACE_SAVING },
    { "Lunch Box", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_LUNCH_BOX },
    { "Main Server Chassis", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_MAIN_SERVER_CHASSIS },
    { "Expansion Chassis", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_EXPANSION_CHASSIS },
    { "SubChassis", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_SUB_CHASSIS },
    { "Bus Expansion Chassis", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_BUS_EXPANSION_CHASSIS },
    { "Peripheral Chassis", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_PERIPHERAL_CHASSIS },
    { "RAID Chassis", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_RAID_CHASSIS },
    { "Rack Mount Chassis", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_RACK_MOUNT_CHASSIS },
    { "Sealed-case PC", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_SEALED_CASE_PC },
    { "Multi-system chassis", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_MULTI_SYSTEM_CHASSIS },
    { "Compact PCI", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_COMPACT_PCI },
    { "Advanced TCA", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_ADVANCED_TCA },
    { "Blade", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_BLADE },
    { "Blade Enclosure", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_BLADE_ENCLOSURE },
    { "Tablet", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_TABLET },
    { "Convertible", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_CONVERTIBLE },
    { "Detachable", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_DETACHABLE },
    { "IoT Gateway", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_IOT_GATEWAY },
    { "Embedded PC", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_EMBEDDED_PC },
    { "Mini PC", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_MINI_PC },
    { "Stick PC", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_STICK_PC }
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType3StateEnum[] = {
    { "Other", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_STATE_OTHER },
    { "Unknown", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_STATE_UNKNOWN },
    { "Safe", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_STATE_SAFE },
    { "Warning", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_STATE_WARNING },
    { "Critical", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_STATE_CRITICAL },
    { "Non-recoverable", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_STATE_NON_RECOVERABLE },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType3SecurityStatusEnum[] = {
    { "Other", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_SECURITY_STATE_OTHER },
    { "Unknown", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_SECURITY_STATE_UNKNOWN },
    { "None", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_SECURITY_STATE_NONE },
    { "External interface locked out", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_SECURITY_STATE_EXTERNAL_INTERFACE_LOCKED_OUT },
    { "External interface enabled", SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_SECURITY_STATE_EXTERNAL_INTERFACE_ENABLED },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType3FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(3, "Manufacturer", Manufacturer),
    SMBIOS_DEFINE_FIELD_UINT(3, "Type", Type.Value),
    SMBIOS_DEFINE_BIT_FIELD("Type", 0, 7, SmbiosDataTypeEnum, SMBIOS_FIELD_ENUM_VALUES(SmbiosType3SecurityStatusEnum)),
    SMBIOS_DEFINE_FIELD_BIT("Chassis lock is present", 7),
    SMBIOS_DEFINE_FIELD_STRING(3, "Version", Version),
    SMBIOS_DEFINE_FIELD_STRING(3, "Serial Number", SerialNumber),
    SMBIOS_DEFINE_FIELD_STRING(3, "Asset Tag Number", AssetTagNumber),
    SMBIOS_DEFINE_FIELD_ENUM(3, "Boot-up State", BootUpState, SmbiosType3StateEnum),
    SMBIOS_DEFINE_FIELD_ENUM(3, "Power Supply State", PowerSupplyState, SmbiosType3StateEnum),
    SMBIOS_DEFINE_FIELD_ENUM(3, "Thermal State", ThermalState, SmbiosType3StateEnum),
    SMBIOS_DEFINE_FIELD_ENUM(3, "Security Status", SecurityStatus, SmbiosType3SecurityStatusEnum),
    SMBIOS_DEFINE_FIELD_UINT(3, "OEM-defined", OEMDefined),
    SMBIOS_DEFINE_FIELD_UINT(3, "Height", Height),
    SMBIOS_DEFINE_FIELD_UINT(3, "Number of Power Cords", NumberOfPowerCords),
    SMBIOS_DEFINE_FIELD_UINT(3, "Contained Element Count", ContainedElementCount),
    SMBIOS_DEFINE_FIELD_UINT(3, "Contained Element Record Length", ContainedElementRecordLength),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType4TypeEnum[] = {
    { "Other", SMBIOS_PROCESSOR_TYPE_OTHER },
    { "Unknown", SMBIOS_PROCESSOR_TYPE_UNKNOWN },
    { "Central Processor", SMBIOS_PROCESSOR_TYPE_CENTRAL_PROCESSOR },
    { "Math Processor", SMBIOS_PROCESSOR_TYPE_MATH_PROCESSOR },
    { "DSP Processor", SMBIOS_PROCESSOR_TYPE_DSP_PROCESSOR },
    { "Video Processor", SMBIOS_PROCESSOR_TYPE_VIDEO_PROCESSOR },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType4FamilyEnum[] = {
    { u8"Other", SMBIOS_PROCESSOR_FAMILY_OTHER },
    { u8"Unknown", SMBIOS_PROCESSOR_FAMILY_UNKNOWN },
    { u8"8086", SMBIOS_PROCESSOR_FAMILY_8086 },
    { u8"80286", SMBIOS_PROCESSOR_FAMILY_80286 },
    { u8"Intel386™ processor", SMBIOS_PROCESSOR_FAMILY_INTEL386_PROCESSOR },
    { u8"Intel486™ processor", SMBIOS_PROCESSOR_FAMILY_INTEL486_PROCESSOR },
    { u8"8087", SMBIOS_PROCESSOR_FAMILY_8087 },
    { u8"80287", SMBIOS_PROCESSOR_FAMILY_80287 },
    { u8"80387", SMBIOS_PROCESSOR_FAMILY_80387 },
    { u8"80487", SMBIOS_PROCESSOR_FAMILY_80487 },
    { u8"Intel® Pentium® processor", SMBIOS_PROCESSOR_FAMILY_INTEL_PENTIUM_PROCESSOR },
    { u8"Pentium® Pro processor", SMBIOS_PROCESSOR_FAMILY_PENTIUM_PRO_PROCESSOR },
    { u8"Pentium® II processor", SMBIOS_PROCESSOR_FAMILY_PENTIUM_II_PROCESSOR },
    { u8"Pentium® processor with MMX™ technology", SMBIOS_PROCESSOR_FAMILY_PENTIUM_PROCESSOR_WITH_MMX_TECHNOLOGY },
    { u8"Intel® Celeron® processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CELERON_PROCESSOR },
    { u8"Pentium® II Xeon® processor", SMBIOS_PROCESSOR_FAMILY_PENTIUM_II_XEON_PROCESSOR },
    { u8"Pentium® III processor", SMBIOS_PROCESSOR_FAMILY_PENTIUM_III_PROCESSOR },
    { u8"M1 Family", SMBIOS_PROCESSOR_FAMILY_M1_FAMILY },
    { u8"M2 Family", SMBIOS_PROCESSOR_FAMILY_M2_FAMILY },
    { u8"Intel® Celeron® M processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CELERON_M_PROCESSOR },
    { u8"Intel® Pentium® 4 HT processor", SMBIOS_PROCESSOR_FAMILY_INTEL_PENTIUM_4_HT_PROCESSOR },
    { u8"Intel® Processor", SMBIOS_PROCESSOR_FAMILY_INTEL_PROCESSOR },
    { u8"AMD Duron™ Processor Family [1]", SMBIOS_PROCESSOR_FAMILY_AMD_DURON_PROCESSOR_FAMILY_1 },
    { u8"K5 Family [1]", SMBIOS_PROCESSOR_FAMILY_K5_FAMILY_1 },
    { u8"K6 Family [1]", SMBIOS_PROCESSOR_FAMILY_K6_FAMILY_1 },
    { u8"K6-2 [1]", SMBIOS_PROCESSOR_FAMILY_K6_2_1 },
    { u8"K6-3 [1]", SMBIOS_PROCESSOR_FAMILY_K6_3_1 },
    { u8"AMD Athlon™ Processor Family [1]", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_PROCESSOR_FAMILY_1 },
    { u8"AMD29000 Family", SMBIOS_PROCESSOR_FAMILY_AMD29000_FAMILY },
    { u8"K6-2+", SMBIOS_PROCESSOR_FAMILY_K6_2_PLUS },
    { u8"Power PC Family", SMBIOS_PROCESSOR_FAMILY_POWER_PC_FAMILY },
    { u8"Power PC 601", SMBIOS_PROCESSOR_FAMILY_POWER_PC_601 },
    { u8"Power PC 603", SMBIOS_PROCESSOR_FAMILY_POWER_PC_603 },
    { u8"Power PC 603+", SMBIOS_PROCESSOR_FAMILY_POWER_PC_603_PLUS },
    { u8"Power PC 604", SMBIOS_PROCESSOR_FAMILY_POWER_PC_604 },
    { u8"Power PC 620", SMBIOS_PROCESSOR_FAMILY_POWER_PC_620 },
    { u8"Power PC x704", SMBIOS_PROCESSOR_FAMILY_POWER_PC_X704 },
    { u8"Power PC 750", SMBIOS_PROCESSOR_FAMILY_POWER_PC_750 },
    { u8"Intel® Core™ Duo processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_DUO_PROCESSOR },
    { u8"Intel® Core™ Duo mobile processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_DUO_MOBILE_PROCESSOR },
    { u8"Intel® Core™ Solo mobile processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_SOLO_MOBILE_PROCESSOR },
    { u8"Intel® Atom™ processor", SMBIOS_PROCESSOR_FAMILY_INTEL_ATOM_PROCESSOR },
    { u8"Intel® Core™ M processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_M_PROCESSOR },
    { u8"Intel® Core™ m3 processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_M3_PROCESSOR },
    { u8"Intel® Core™ m5 processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_M5_PROCESSOR },
    { u8"Intel® Core™ m7 processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_M7_PROCESSOR },
    { u8"Alpha Family [2]", SMBIOS_PROCESSOR_FAMILY_ALPHA_FAMILY_2 },
    { u8"Alpha 21064", SMBIOS_PROCESSOR_FAMILY_ALPHA_21064 },
    { u8"Alpha 21066", SMBIOS_PROCESSOR_FAMILY_ALPHA_21066 },
    { u8"Alpha 21164", SMBIOS_PROCESSOR_FAMILY_ALPHA_21164 },
    { u8"Alpha 21164PC", SMBIOS_PROCESSOR_FAMILY_ALPHA_21164PC },
    { u8"Alpha 21164a", SMBIOS_PROCESSOR_FAMILY_ALPHA_21164A },
    { u8"Alpha 21264", SMBIOS_PROCESSOR_FAMILY_ALPHA_21264 },
    { u8"Alpha 21364", SMBIOS_PROCESSOR_FAMILY_ALPHA_21364 },
    { u8"AMD Turion™ II Ultra Dual-Core Mobile M Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_TURION_II_ULTRA_DUAL_CORE_MOBILE_M_PROCESSOR_FAMILY },
    { u8"AMD Turion™ II Dual-Core Mobile M Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_TURION_II_DUAL_CORE_MOBILE_M_PROCESSOR_FAMILY },
    { u8"AMD Athlon™ II Dual-Core M Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_II_DUAL_CORE_M_PROCESSOR_FAMILY },
    { u8"AMD Opteron™ 6100 Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_6100_SERIES_PROCESSOR },
    { u8"AMD Opteron™ 4100 Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_4100_SERIES_PROCESSOR },
    { u8"AMD Opteron™ 6200 Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_6200_SERIES_PROCESSOR },
    { u8"AMD Opteron™ 4200 Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_4200_SERIES_PROCESSOR },
    { u8"AMD FX™ Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_FX_SERIES_PROCESSOR },
    { u8"MIPS Family", SMBIOS_PROCESSOR_FAMILY_MIPS_FAMILY },
    { u8"MIPS R4000", SMBIOS_PROCESSOR_FAMILY_MIPS_R4000 },
    { u8"MIPS R4200", SMBIOS_PROCESSOR_FAMILY_MIPS_R4200 },
    { u8"MIPS R4400", SMBIOS_PROCESSOR_FAMILY_MIPS_R4400 },
    { u8"MIPS R4600", SMBIOS_PROCESSOR_FAMILY_MIPS_R4600 },
    { u8"MIPS R10000", SMBIOS_PROCESSOR_FAMILY_MIPS_R10000 },
    { u8"AMD C-Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_C_SERIES_PROCESSOR },
    { u8"AMD E-Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_E_SERIES_PROCESSOR },
    { u8"AMD A-Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_A_SERIES_PROCESSOR },
    { u8"AMD G-Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_G_SERIES_PROCESSOR },
    { u8"AMD Z-Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_Z_SERIES_PROCESSOR },
    { u8"AMD R-Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_R_SERIES_PROCESSOR },
    { u8"AMD Opteron™ 4300 Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_4300_SERIES_PROCESSOR },
    { u8"AMD Opteron™ 6300 Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_6300_SERIES_PROCESSOR },
    { u8"AMD Opteron™ 3300 Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_3300_SERIES_PROCESSOR },
    { u8"AMD FirePro™ Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_FIREPRO_SERIES_PROCESSOR },
    { u8"SPARC Family", SMBIOS_PROCESSOR_FAMILY_SPARC_FAMILY },
    { u8"SuperSPARC", SMBIOS_PROCESSOR_FAMILY_SUPERSPARC },
    { u8"microSPARC II", SMBIOS_PROCESSOR_FAMILY_MICROSPARC_II },
    { u8"microSPARC IIep", SMBIOS_PROCESSOR_FAMILY_MICROSPARC_IIEP },
    { u8"UltraSPARC", SMBIOS_PROCESSOR_FAMILY_ULTRASPARC },
    { u8"UltraSPARC II", SMBIOS_PROCESSOR_FAMILY_ULTRASPARC_II },
    { u8"UltraSPARC Iii", SMBIOS_PROCESSOR_FAMILY_ULTRASPARC_Iii },
    { u8"UltraSPARC III", SMBIOS_PROCESSOR_FAMILY_ULTRASPARC_III },
    { u8"UltraSPARC IIIi", SMBIOS_PROCESSOR_FAMILY_ULTRASPARC_IIIi },
    { u8"68040 Family", SMBIOS_PROCESSOR_FAMILY_68040_FAMILY },
    { u8"68xxx", SMBIOS_PROCESSOR_FAMILY_68XXX },
    { u8"68000", SMBIOS_PROCESSOR_FAMILY_68000 },
    { u8"68010", SMBIOS_PROCESSOR_FAMILY_68010 },
    { u8"68020", SMBIOS_PROCESSOR_FAMILY_68020 },
    { u8"68030", SMBIOS_PROCESSOR_FAMILY_68030 },
    { u8"AMD Athlon(TM) X4 Quad-Core Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_X4_QUAD_CORE_PROCESSOR_FAMILY },
    { u8"AMD Opteron(TM) X1000 Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_X1000_SERIES_PROCESSOR },
    { u8"AMD Opteron(TM) X2000 Series APU", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_X2000_SERIES_APU },
    { u8"AMD Opteron(TM) A-Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_A_SERIES_PROCESSOR },
    { u8"AMD Opteron(TM) X3000 Series APU", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_X3000_SERIES_APU },
    { u8"AMD Zen Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ZEN_PROCESSOR_FAMILY },
    { u8"Hobbit Family", SMBIOS_PROCESSOR_FAMILY_HOBBIT_FAMILY },
    { u8"Crusoe™ TM5000 Family", SMBIOS_PROCESSOR_FAMILY_CRUSOE_TM5000_FAMILY },
    { u8"Crusoe™ TM3000 Family", SMBIOS_PROCESSOR_FAMILY_CRUSOE_TM3000_FAMILY },
    { u8"Efficeon™ TM8000 Family", SMBIOS_PROCESSOR_FAMILY_EFFICEON_TM8000_FAMILY },
    { u8"Weitek", SMBIOS_PROCESSOR_FAMILY_WEITEK },
    { u8"Itanium™ processor", SMBIOS_PROCESSOR_FAMILY_ITANIUM_PROCESSOR },
    { u8"AMD Athlon™ 64 Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_64_PROCESSOR_FAMILY },
    { u8"AMD Opteron™ Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_PROCESSOR_FAMILY },
    { u8"AMD Sempron™ Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_SEMPRON_PROCESSOR_FAMILY },
    { u8"AMD Turion™ 64 Mobile Technology", SMBIOS_PROCESSOR_FAMILY_AMD_TURION_64_MOBILE_TECHNOLOGY },
    { u8"Dual-Core AMD Opteron™ Processor Family", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_AMD_OPTERON_PROCESSOR_FAMILY },
    { u8"AMD Athlon™ 64 X2 Dual-Core Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_64_X2_DUAL_CORE_PROCESSOR_FAMILY },
    { u8"AMD Turion™ 64 X2 Mobile Technology", SMBIOS_PROCESSOR_FAMILY_AMD_TURION_64_X2_MOBILE_TECHNOLOGY },
    { u8"Quad-Core AMD Opteron™ Processor Family", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_AMD_OPTERON_PROCESSOR_FAMILY },
    { u8"Third-Generation AMD Opteron™ Processor Family", SMBIOS_PROCESSOR_FAMILY_THIRD_GENERATION_AMD_OPTERON_PROCESSOR_FAMILY },
    { u8"AMD Phenom™ FX Quad-Core Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_PHENOM_FX_QUAD_CORE_PROCESSOR_FAMILY },
    { u8"AMD Phenom™ X4 Quad-Core Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_PHENOM_X4_QUAD_CORE_PROCESSOR_FAMILY },
    { u8"AMD Phenom™ X2 Dual-Core Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_PHENOM_X2_DUAL_CORE_PROCESSOR_FAMILY },
    { u8"AMD Athlon™ X2 Dual-Core Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_X2_DUAL_CORE_PROCESSOR_FAMILY },
    { u8"PA-RISC Family", SMBIOS_PROCESSOR_FAMILY_PA_RISC_FAMILY },
    { u8"PA-RISC 8500", SMBIOS_PROCESSOR_FAMILY_PA_RISC_8500 },
    { u8"PA-RISC 8000", SMBIOS_PROCESSOR_FAMILY_PA_RISC_8000 },
    { u8"PA-RISC 7300LC", SMBIOS_PROCESSOR_FAMILY_PA_RISC_7300LC },
    { u8"PA-RISC 7200", SMBIOS_PROCESSOR_FAMILY_PA_RISC_7200 },
    { u8"PA-RISC 7100LC", SMBIOS_PROCESSOR_FAMILY_PA_RISC_7100LC },
    { u8"PA-RISC 7100", SMBIOS_PROCESSOR_FAMILY_PA_RISC_7100 },
    { u8"V30 Family", SMBIOS_PROCESSOR_FAMILY_V30_FAMILY },
    { u8"Quad-Core Intel® Xeon® processor 3200 Series", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON_PROCESSOR_3200_SERIES },
    { u8"Dual-Core Intel® Xeon® processor 3000 Series", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_3000_SERIES },
    { u8"Quad-Core Intel® Xeon® processor 5300 Series", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON_PROCESSOR_5300_SERIES },
    { u8"Dual-Core Intel® Xeon® processor 5100 Series", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_5100_SERIES },
    { u8"Dual-Core Intel® Xeon® processor 5000 Series", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_5000_SERIES },
    { u8"Dual-Core Intel® Xeon® processor LV", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_LV },
    { u8"Dual-Core Intel® Xeon® processor ULV", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_ULV },
    { u8"Dual-Core Intel® Xeon® processor 7100 Series", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_7100_SERIES },
    { u8"Quad-Core Intel® Xeon® processor 5400 Series", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON_PROCESSOR_5400_SERIES },
    { u8"Quad-Core Intel® Xeon® processor", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON_PROCESSOR },
    { u8"Dual-Core Intel® Xeon® processor 5200 Series", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_5200_SERIES },
    { u8"Dual-Core Intel® Xeon® processor 7200 Series", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_7200_SERIES },
    { u8"Quad-Core Intel® Xeon® processor 7300 Series", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON_PROCESSOR_7300_SERIES },
    { u8"Quad-Core Intel® Xeon® processor 7400 Series", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON_PROCESSOR_7400_SERIES },
    { u8"Multi-Core Intel® Xeon® processor 7400 Series", SMBIOS_PROCESSOR_FAMILY_MULTI_CORE_INTEL_XEON_PROCESSOR_7400_SERIES },
    { u8"Pentium® III Xeon® processor", SMBIOS_PROCESSOR_FAMILY_PENTIUM_III_XEON_PROCESSOR },
    { u8"Pentium® III Processor with Intel® SpeedStep™ Technology", SMBIOS_PROCESSOR_FAMILY_PENTIUM_III_PROCESSOR_WITH_INTEL_SPEEDSTEP_TECHNOLOGY },
    { u8"Pentium® 4 Processor", SMBIOS_PROCESSOR_FAMILY_PENTIUM_4_PROCESSOR },
    { u8"Intel® Xeon® processor", SMBIOS_PROCESSOR_FAMILY_INTEL_XEON_PROCESSOR },
    { u8"AS400 Family", SMBIOS_PROCESSOR_FAMILY_AS400_FAMILY },
    { u8"Intel® Xeon® processor MP", SMBIOS_PROCESSOR_FAMILY_INTEL_XEON_PROCESSOR_MP },
    { u8"AMD Athlon™ XP Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_XP_PROCESSOR_FAMILY },
    { u8"AMD Athlon™ MP Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_MP_PROCESSOR_FAMILY },
    { u8"Intel® Itanium® 2 processor", SMBIOS_PROCESSOR_FAMILY_INTEL_ITANIUM_2_PROCESSOR },
    { u8"Intel® Pentium® M processor", SMBIOS_PROCESSOR_FAMILY_INTEL_PENTIUM_M_PROCESSOR },
    { u8"Intel® Celeron® D processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CELERON_D_PROCESSOR },
    { u8"Intel® Pentium® D processor", SMBIOS_PROCESSOR_FAMILY_INTEL_PENTIUM_D_PROCESSOR },
    { u8"Intel® Pentium® Processor Extreme Edition", SMBIOS_PROCESSOR_FAMILY_INTEL_PENTIUM_PROCESSOR_EXTREME_EDITION },
    { u8"Intel® Core™ Solo Processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_SOLO_PROCESSOR },
    { u8"Intel® Core™ 2 Duo Processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_2_DUO_PROCESSOR },
    { u8"Intel® Core™ 2 Solo processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_2_SOLO_PROCESSOR },
    { u8"Intel® Core™ 2 Extreme processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_2_EXTREME_PROCESSOR },
    { u8"Intel® Core™ 2 Quad processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_2_QUAD_PROCESSOR },
    { u8"Intel® Core™ 2 Extreme mobile processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_2_EXTREME_MOBILE_PROCESSOR },
    { u8"Intel® Core™ 2 Duo mobile processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_2_DUO_MOBILE_PROCESSOR },
    { u8"Intel® Core™ 2 Solo mobile processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_2_SOLO_MOBILE_PROCESSOR },
    { u8"Intel® Core™ i7 processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_I7_PROCESSOR },
    { u8"Dual-Core Intel® Celeron® processor", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_CELERON_PROCESSOR },
    { u8"IBM390 Family", SMBIOS_PROCESSOR_FAMILY_IBM390_FAMILY },
    { u8"G4", SMBIOS_PROCESSOR_FAMILY_G4 },
    { u8"G5", SMBIOS_PROCESSOR_FAMILY_G5 },
    { u8"ESA/390 G6", SMBIOS_PROCESSOR_FAMILY_ESA_390_G6 },
    { u8"z/Architecture base", SMBIOS_PROCESSOR_FAMILY_Z_ARCHITECTURE_BASE },
    { u8"Intel® Core™ i5 processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_I5_PROCESSOR },
    { u8"Intel® Core™ i3 processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_I3_PROCESSOR },
    { u8"Intel® Core™ i9 processor", SMBIOS_PROCESSOR_FAMILY_INTEL_CORE_I9_PROCESSOR },
    { u8"Intel® Xeon® D Processor family", SMBIOS_PROCESSOR_FAMILY_INTEL_XEON_D_PROCESSOR_FAMILY },
    { u8"VIA C7™-M Processor Family", SMBIOS_PROCESSOR_FAMILY_VIA_C7_M_PROCESSOR_FAMILY },
    { u8"VIA C7™-D Processor Family", SMBIOS_PROCESSOR_FAMILY_VIA_C7_D_PROCESSOR_FAMILY },
    { u8"VIA C7™ Processor Family", SMBIOS_PROCESSOR_FAMILY_VIA_C7_PROCESSOR_FAMILY },
    { u8"VIA Eden™ Processor Family", SMBIOS_PROCESSOR_FAMILY_VIA_EDEN_PROCESSOR_FAMILY },
    { u8"Multi-Core Intel® Xeon® processor", SMBIOS_PROCESSOR_FAMILY_MULTI_CORE_INTEL_XEON_PROCESSOR },
    { u8"Dual-Core Intel® Xeon® processor 3xxx Series", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_3XXX_SERIES },
    { u8"Quad-Core Intel® Xeon® processor 3xxx Series", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON_PROCESSOR_3XXX_SERIES },
    { u8"VIA Nano™ Processor Family", SMBIOS_PROCESSOR_FAMILY_VIA_NANO_PROCESSOR_FAMILY },
    { u8"Dual-Core Intel® Xeon® processor 5xxx Series", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_5XXX_SERIES },
    { u8"Quad-Core Intel® Xeon® processor 5xxx Series", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON_PROCESSOR_5XXX_SERIES },
    { u8"Dual-Core Intel® Xeon® processor 7xxx Series", SMBIOS_PROCESSOR_FAMILY_DUAL_CORE_INTEL_XEON_PROCESSOR_7XXX_SERIES },
    { u8"Quad-Core Intel® Xeon® processor 7xxx Series", SMBIOS_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON_PROCESSOR_7XXX_SERIES },
    { u8"Multi-Core Intel® Xeon® processor 7xxx Series", SMBIOS_PROCESSOR_FAMILY_MULTI_CORE_INTEL_XEON_PROCESSOR_7XXX_SERIES },
    { u8"Multi-Core Intel® Xeon® processor 3400 Series", SMBIOS_PROCESSOR_FAMILY_MULTI_CORE_INTEL_XEON_PROCESSOR_3400_SERIES },
    { u8"AMD Opteron™ 3000 Series Processor", SMBIOS_PROCESSOR_FAMILY_AMD_OPTERON_3000_SERIES_PROCESSOR },
    { u8"AMD Sempron™ II Processor", SMBIOS_PROCESSOR_FAMILY_AMD_SEMPRON_II_PROCESSOR },
    { u8"Embedded AMD Opteron™ Quad-Core Processor Family", SMBIOS_PROCESSOR_FAMILY_EMBEDDED_AMD_OPTERON_QUAD_CORE_PROCESSOR_FAMILY },
    { u8"AMD Phenom™ Triple-Core Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_PHENOM_TRIPLE_CORE_PROCESSOR_FAMILY },
    { u8"AMD Turion™ Ultra Dual-Core Mobile Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_TURION_ULTRA_DUAL_CORE_MOBILE_PROCESSOR_FAMILY },
    { u8"AMD Turion™ Dual-Core Mobile Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_TURION_DUAL_CORE_MOBILE_PROCESSOR_FAMILY },
    { u8"AMD Athlon™ Dual-Core Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_DUAL_CORE_PROCESSOR_FAMILY },
    { u8"AMD Sempron™ SI Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_SEMPRON_SI_PROCESSOR_FAMILY },
    { u8"AMD Phenom™ II Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_PHENOM_II_PROCESSOR_FAMILY },
    { u8"AMD Athlon™ II Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_ATHLON_II_PROCESSOR_FAMILY },
    { u8"Six-Core AMD Opteron™ Processor Family", SMBIOS_PROCESSOR_FAMILY_SIX_CORE_AMD_OPTERON_PROCESSOR_FAMILY },
    { u8"AMD Sempron™ M Processor Family", SMBIOS_PROCESSOR_FAMILY_AMD_SEMPRON_M_PROCESSOR_FAMILY },
    { u8"i860", SMBIOS_PROCESSOR_FAMILY_I860 },
    { u8"i960", SMBIOS_PROCESSOR_FAMILY_I960 },
    { u8"(See Processor Family 2)", SMBIOS_PROCESSOR_FAMILY_EXTENSION_INDICATOR },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType4CpuStatusEnum[] = {
    { "Unknown", SMBIOS_PROCESSOR_CPU_STATUS_UNKNOWN },
    { "CPU Enabled", SMBIOS_PROCESSOR_CPU_STATUS_ENABLED },
    { "CPU Disabled by User through Firmware Setup", SMBIOS_PROCESSOR_CPU_STATUS_DISABLED_BY_USER },
    { "CPU Disabled By firmware (POST Error)", SMBIOS_PROCESSOR_CPU_STATUS_DISABLED_BY_FIRMWARE },
    { "CPU is Idle, waiting to be enabled", SMBIOS_PROCESSOR_CPU_STATUS_IDLE },
    { "Other", SMBIOS_PROCESSOR_CPU_STATUS_OTHER },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType4UpgradeEnum[] = {
    { "Other", SMBIOS_PROCESSOR_UPGRADE_OTHER },
    { "Unknown", SMBIOS_PROCESSOR_UPGRADE_UNKNOWN },
    { "Daughter Board", SMBIOS_PROCESSOR_UPGRADE_DAUGHTER_BOARD },
    { "ZIF Socket", SMBIOS_PROCESSOR_UPGRADE_ZIF_SOCKET },
    { "Replaceable Piggy Back", SMBIOS_PROCESSOR_UPGRADE_REPLACEABLE_PIGGY_BACK },
    { "None", SMBIOS_PROCESSOR_UPGRADE_NONE },
    { "LIF Socket", SMBIOS_PROCESSOR_UPGRADE_LIF_SOCKET },
    { "Slot 1", SMBIOS_PROCESSOR_UPGRADE_SLOT_1 },
    { "Slot 2", SMBIOS_PROCESSOR_UPGRADE_SLOT_2 },
    { "370-pin socket", SMBIOS_PROCESSOR_UPGRADE_370_PIN_SOCKET },
    { "Slot A", SMBIOS_PROCESSOR_UPGRADE_SLOT_A },
    { "Slot M", SMBIOS_PROCESSOR_UPGRADE_SLOT_M },
    { "Socket 423", SMBIOS_PROCESSOR_UPGRADE_SOCKET_423 },
    { "Socket A (Socket 462)", SMBIOS_PROCESSOR_UPGRADE_SOCKET_A },
    { "Socket 478", SMBIOS_PROCESSOR_UPGRADE_SOCKET_478 },
    { "Socket 754", SMBIOS_PROCESSOR_UPGRADE_SOCKET_754 },
    { "Socket 940", SMBIOS_PROCESSOR_UPGRADE_SOCKET_940 },
    { "Socket 939", SMBIOS_PROCESSOR_UPGRADE_SOCKET_939 },
    { "Socket mPGA604", SMBIOS_PROCESSOR_UPGRADE_SOCKET_mPGA604 },
    { "Socket LGA771", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA771 },
    { "Socket LGA775", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA775 },
    { "Socket S1", SMBIOS_PROCESSOR_UPGRADE_SOCKET_S1 },
    { "Socket AM2", SMBIOS_PROCESSOR_UPGRADE_SOCKET_AM2 },
    { "Socket F (1207)", SMBIOS_PROCESSOR_UPGRADE_SOCKET_F },
    { "Socket LGA1366", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1366 },
    { "Socket G34", SMBIOS_PROCESSOR_UPGRADE_SOCKET_G34 },
    { "Socket AM3", SMBIOS_PROCESSOR_UPGRADE_SOCKET_AM3 },
    { "Socket C32", SMBIOS_PROCESSOR_UPGRADE_SOCKET_C32 },
    { "Socket LGA1156", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1156 },
    { "Socket LGA1567", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1567 },
    { "Socket PGA988A", SMBIOS_PROCESSOR_UPGRADE_SOCKET_PGA988A },
    { "Socket BGA1288", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1288 },
    { "Socket rPGA988B", SMBIOS_PROCESSOR_UPGRADE_SOCKET_rPGA988B },
    { "Socket BGA1023", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1023 },
    { "Socket BGA1224", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1224 },
    { "Socket LGA1155", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1155 },
    { "Socket LGA1356", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1356 },
    { "Socket LGA2011", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA2011 },
    { "Socket FS1", SMBIOS_PROCESSOR_UPGRADE_SOCKET_FS1 },
    { "Socket FS2", SMBIOS_PROCESSOR_UPGRADE_SOCKET_FS2 },
    { "Socket FM1", SMBIOS_PROCESSOR_UPGRADE_SOCKET_FM1 },
    { "Socket FM2", SMBIOS_PROCESSOR_UPGRADE_SOCKET_FM2 },
    { "Socket LGA2011-3", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA2011_3 },
    { "Socket LGA2011-3", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1356_3 },
    { "Socket LGA1150", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1150 },
    { "Socket BGA1168", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1168 },
    { "Socket BGA1234", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1234 },
    { "Socket BGA1364", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1364 },
    { "Socket AM4", SMBIOS_PROCESSOR_UPGRADE_SOCKET_AM4 },
    { "Socket LGA1151", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1151 },
    { "Socket BGA1356", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1356 },
    { "Socket BGA1440", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1440 },
    { "Socket BGA1515", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1515 },
    { "Socket LGA3647-1", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA3647_1 },
    { "Socket SP3", SMBIOS_PROCESSOR_UPGRADE_SOCKET_SP3 },
    { "Socket SP3r2", SMBIOS_PROCESSOR_UPGRADE_SOCKET_SP3r2 },
    { "Socket LGA2066", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA2066 },
    { "Socket BGA1392", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1392 },
    { "Socket BGA1510", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1510 },
    { "Socket BGA1528", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1528 },
    { "Socket LGA4189", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA4189 },
    { "Socket LGA1200", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1200 },
    { "Socket LGA4677", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA4677 },
    { "Socket LGA1700", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1700 },
    { "Socket BGA1744", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1744 },
    { "Socket BGA1781", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1781 },
    { "Socket BGA1211", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1211 },
    { "Socket BGA2422", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA2422 },
    { "Socket LGA1211", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1211 },
    { "Socket LGA2422", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA2422 },
    { "Socket LGA5773", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA5773 },
    { "Socket BGA5773", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA5773 },
    { "Socket AM5", SMBIOS_PROCESSOR_UPGRADE_SOCKET_AM5 },
    { "Socket SP5", SMBIOS_PROCESSOR_UPGRADE_SOCKET_SP5 },
    { "Socket SP6", SMBIOS_PROCESSOR_UPGRADE_SOCKET_SP6 },
    { "Socket BGA883", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA883 },
    { "Socket BGA1190", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1190 },
    { "Socket BGA4129", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA4129 },
    { "Socket LGA4710", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA4710 },
    { "Socket LGA7529", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA7529 },
    { "Socket BGA1964", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1964 },
    { "Socket BGA1792", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA1792 },
    { "Socket BGA2049", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA2049 },
    { "Socket BGA2551", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA2551 },
    { "Socket LGA1851", SMBIOS_PROCESSOR_UPGRADE_SOCKET_LGA1851 },
    { "Socket BGA2114", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA2114 },
    { "Socket BGA2833", SMBIOS_PROCESSOR_UPGRADE_SOCKET_BGA2833 },
    { "Invalid", SMBIOS_PROCESSOR_UPGRADE_INVALID },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType4Family2Enum[] = {
    { u8"ARMv7", SMBIOS_PROCESSOR_FAMILY_2_ARMV7 },
    { u8"ARMv8", SMBIOS_PROCESSOR_FAMILY_2_ARMV8 },
    { u8"ARMv9", SMBIOS_PROCESSOR_FAMILY_2_ARMV9 },
    { u8"SH-3", SMBIOS_PROCESSOR_FAMILY_2_SH_3 },
    { u8"SH-4", SMBIOS_PROCESSOR_FAMILY_2_SH_4 },
    { u8"ARM", SMBIOS_PROCESSOR_FAMILY_2_ARM },
    { u8"StrongARM", SMBIOS_PROCESSOR_FAMILY_2_STRONGARM },
    { u8"6x86", SMBIOS_PROCESSOR_FAMILY_2_6X86 },
    { u8"MediaGX", SMBIOS_PROCESSOR_FAMILY_2_MEDIAGX },
    { u8"MII", SMBIOS_PROCESSOR_FAMILY_2_MII },
    { u8"WinChip", SMBIOS_PROCESSOR_FAMILY_2_WINCHIP },
    { u8"DSP", SMBIOS_PROCESSOR_FAMILY_2_DSP },
    { u8"Video Processor", SMBIOS_PROCESSOR_FAMILY_2_VIDEO_PROCESSOR },
    { u8"RISC-V RV32", SMBIOS_PROCESSOR_FAMILY_2_RISC_V_RV32 },
    { u8"RISC-V RV64", SMBIOS_PROCESSOR_FAMILY_2_RISC_V_RV64 },
    { u8"RISC-V RV128", SMBIOS_PROCESSOR_FAMILY_2_RISC_V_RV128 },
    { u8"LoongArch", SMBIOS_PROCESSOR_FAMILY_2_LOONGARCH },
    { u8"Loongson™ 1 Processor Family", SMBIOS_PROCESSOR_FAMILY_2_LOONGSON_1_PROCESSOR_FAMILY },
    { u8"Loongson™ 2 Processor Family", SMBIOS_PROCESSOR_FAMILY_2_LOONGSON_2_PROCESSOR_FAMILY },
    { u8"Loongson™ 3 Processor Family", SMBIOS_PROCESSOR_FAMILY_2_LOONGSON_3_PROCESSOR_FAMILY },
    { u8"Loongson™ 2K Processor Family", SMBIOS_PROCESSOR_FAMILY_2_LOONGSON_2K_PROCESSOR_FAMILY },
    { u8"Loongson™ 3A Processor Family", SMBIOS_PROCESSOR_FAMILY_2_LOONGSON_3A_PROCESSOR_FAMILY },
    { u8"Loongson™ 3B Processor Family", SMBIOS_PROCESSOR_FAMILY_2_LOONGSON_3B_PROCESSOR_FAMILY },
    { u8"Loongson™ 3C Processor Family", SMBIOS_PROCESSOR_FAMILY_2_LOONGSON_3C_PROCESSOR_FAMILY },
    { u8"Loongson™ 3D Processor Family", SMBIOS_PROCESSOR_FAMILY_2_LOONGSON_3D_PROCESSOR_FAMILY },
    { u8"Loongson™ 3E Processor Family", SMBIOS_PROCESSOR_FAMILY_2_LOONGSON_3E_PROCESSOR_FAMILY },
    { u8"Dual-Core Loongson™ 2K Processor 2xxx Series", SMBIOS_PROCESSOR_FAMILY_2_DUAL_CORE_LOONGSON_2K_PROCESSOR_2XXX_SERIES },
    { u8"Quad-Core Loongson™ 3A Processor 5xxx Series", SMBIOS_PROCESSOR_FAMILY_2_QUAD_CORE_LOONGSON_3A_PROCESSOR_5XXX_SERIES },
    { u8"Multi-Core Loongson™ 3A Processor 5xxx Series", SMBIOS_PROCESSOR_FAMILY_2_MULTI_CORE_LOONGSON_3A_PROCESSOR_5XXX_SERIES },
    { u8"Quad-Core Loongson™ 3B Processor 5xxx Series", SMBIOS_PROCESSOR_FAMILY_2_QUAD_CORE_LOONGSON_3B_PROCESSOR_5XXX_SERIES },
    { u8"Multi-Core Loongson™ 3B Processor 5xxx Series", SMBIOS_PROCESSOR_FAMILY_2_MULTI_CORE_LOONGSON_3B_PROCESSOR_5XXX_SERIES },
    { u8"Multi-Core Loongson™ 3C Processor 5xxx Series", SMBIOS_PROCESSOR_FAMILY_2_MULTI_CORE_LOONGSON_3C_PROCESSOR_5XXX_SERIES },
    { u8"Multi-Core Loongson™ 3D Processor 5xxx Series", SMBIOS_PROCESSOR_FAMILY_2_MULTI_CORE_LOONGSON_3D_PROCESSOR_5XXX_SERIES },
    { u8"Intel® Core™ 3", SMBIOS_PROCESSOR_FAMILY_2_INTEL_CORE_3 },
    { u8"Intel® Core™ 5", SMBIOS_PROCESSOR_FAMILY_2_INTEL_CORE_5 },
    { u8"Intel® Core™ 7", SMBIOS_PROCESSOR_FAMILY_2_INTEL_CORE_7 },
    { u8"Intel® Core™ 9", SMBIOS_PROCESSOR_FAMILY_2_INTEL_CORE_9 },
    { u8"Intel® Core™ Ultra 3", SMBIOS_PROCESSOR_FAMILY_2_INTEL_CORE_ULTRA_3 },
    { u8"Intel® Core™ Ultra 5", SMBIOS_PROCESSOR_FAMILY_2_INTEL_CORE_ULTRA_5 },
    { u8"Intel® Core™ Ultra 7", SMBIOS_PROCESSOR_FAMILY_2_INTEL_CORE_ULTRA_7 },
    { u8"Intel® Core™ Ultra 9", SMBIOS_PROCESSOR_FAMILY_2_INTEL_CORE_ULTRA_9 },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType4FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(4, "Socket Designation", SocketDesignation),
    SMBIOS_DEFINE_FIELD_ENUM(4, "Processor Type", Type, SmbiosType4TypeEnum),
    SMBIOS_DEFINE_FIELD_ENUM(4, "Processor Family", Family, SmbiosType4FamilyEnum),
    SMBIOS_DEFINE_FIELD_STRING(4, "Processor Manufacturer", Manufacturer),
    SMBIOS_DEFINE_FIELD_UINT(4, "Processor ID", ID),
    SMBIOS_DEFINE_FIELD_STRING(4, "Processor Version", Version),
    SMBIOS_DEFINE_FIELD_UINT(4, "Voltage", Voltage),
    SMBIOS_DEFINE_FIELD_UINT(4, "External Clock", ExternalClock),
    SMBIOS_DEFINE_FIELD_UINT(4, "Max Speed", MaxSpeed),
    SMBIOS_DEFINE_FIELD_UINT(4, "Current Speed", CurrentSpeed),
    SMBIOS_DEFINE_FIELD_UINT(4, "Status", Status.Value),
    SMBIOS_DEFINE_BIT_FIELD("CPU Status", 0, 3, SmbiosDataTypeEnum, SMBIOS_FIELD_ENUM_VALUES(SmbiosType4CpuStatusEnum)),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 3, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("CPU Socket Populated", 6),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 7),
    SMBIOS_DEFINE_FIELD_ENUM(4, "Processor Upgrade", Upgrade, SmbiosType4UpgradeEnum),
    SMBIOS_DEFINE_FIELD_UINT(4, "L1 Cache Handle", L1CacheHandle),
    SMBIOS_DEFINE_FIELD_UINT(4, "L2 Cache Handle", L2CacheHandle),
    SMBIOS_DEFINE_FIELD_UINT(4, "L3 Cache Handle", L3CacheHandle),
    SMBIOS_DEFINE_FIELD_STRING(4, "Serial Number", SerialNumber),
    SMBIOS_DEFINE_FIELD_STRING(4, "Asset Tag", AssetTag),
    SMBIOS_DEFINE_FIELD_STRING(4, "Part Number", PartNumber),
    SMBIOS_DEFINE_FIELD_UINT(4, "Core Count", CoreCount),
    SMBIOS_DEFINE_FIELD_UINT(4, "Core Enabled", CoreEnabled),
    SMBIOS_DEFINE_FIELD_UINT(4, "Thread Count", ThreadCount),
    SMBIOS_DEFINE_FIELD_UINT(4, "Processor Characteristics", Characteristics.Value),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 0),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 1),
    SMBIOS_DEFINE_FIELD_BIT("64-bit Capable", 2),
    SMBIOS_DEFINE_FIELD_BIT("Multi-Core", 3),
    SMBIOS_DEFINE_FIELD_BIT("Hardware Thread", 4),
    SMBIOS_DEFINE_FIELD_BIT("Execute Protection", 5),
    SMBIOS_DEFINE_FIELD_BIT("Enhanced Virtualization", 6),
    SMBIOS_DEFINE_FIELD_BIT("Power/Performance Control", 7),
    SMBIOS_DEFINE_FIELD_BIT("128-bit Capable", 8),
    SMBIOS_DEFINE_FIELD_BIT("Arm64 SoC ID", 9),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 10, 6, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_ENUM(4, "Processor Family 2", Family2, SmbiosType4Family2Enum),
    SMBIOS_DEFINE_FIELD_UINT(4, "Core Count 2", CoreCount2),
    SMBIOS_DEFINE_FIELD_UINT(4, "Core Enabled 2", CoreEnabled2),
    SMBIOS_DEFINE_FIELD_UINT(4, "Thread Count 2", ThreadCount2),
    SMBIOS_DEFINE_FIELD_UINT(4, "Thread Enabled", ThreadEnabled),
    SMBIOS_DEFINE_FIELD_STRING(4, "Socket Type", SocketType),
};

#define SMBIOS_MEMORY_TYPE_FIELDS\
    SMBIOS_DEFINE_FIELD_BIT("Other", 0),\
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 0),\
    SMBIOS_DEFINE_FIELD_BIT("Standard", 0),\
    SMBIOS_DEFINE_FIELD_BIT("Fast Page Mode", 0),\
    SMBIOS_DEFINE_FIELD_BIT("EDO", 0),\
    SMBIOS_DEFINE_FIELD_BIT("Parity", 0),\
    SMBIOS_DEFINE_FIELD_BIT("ECC", 0),\
    SMBIOS_DEFINE_FIELD_BIT("SIMM", 0),\
    SMBIOS_DEFINE_FIELD_BIT("DIMM", 0),\
    SMBIOS_DEFINE_FIELD_BIT("Burst EDO", 0),\
    SMBIOS_DEFINE_FIELD_BIT("SDRAM", 0),\
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 11, 5, SmbiosDataTypeUInt)

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType5ErrorDetectingMethodEnum[] = {
    { "Other", SMBIOS_MEMORY_CONTROLLER_ERROR_DETECTING_METHOD_OTHER },
    { "Unknown", SMBIOS_MEMORY_CONTROLLER_ERROR_DETECTING_METHOD_UNKNOWN },
    { "None", SMBIOS_MEMORY_CONTROLLER_ERROR_DETECTING_METHOD_NONE },
    { "8-bit Parity", SMBIOS_MEMORY_CONTROLLER_ERROR_DETECTING_METHOD_8BIT_PARITY },
    { "32-bit ECC", SMBIOS_MEMORY_CONTROLLER_ERROR_DETECTING_METHOD_32BIT_ECC },
    { "64-bit ECC", SMBIOS_MEMORY_CONTROLLER_ERROR_DETECTING_METHOD_64BIT_ECC },
    { "128-bit ECC", SMBIOS_MEMORY_CONTROLLER_ERROR_DETECTING_METHOD_128BIT_ECC },
    { "CRC", SMBIOS_MEMORY_CONTROLLER_ERROR_DETECTING_METHOD_CRC },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType5InterleaveEnum[] = {
    { "Other", SMBIOS_MEMORY_CONTROLLER_INTERLEAVE_OTHER },
    { "Unknown", SMBIOS_MEMORY_CONTROLLER_INTERLEAVE_UNKNOWN },
    { "One-Way Interleave", SMBIOS_MEMORY_CONTROLLER_INTERLEAVE_ONE_WAY },
    { "Two-Way Interleave", SMBIOS_MEMORY_CONTROLLER_INTERLEAVE_TWO_WAY },
    { "Four-Way Interleave", SMBIOS_MEMORY_CONTROLLER_INTERLEAVE_FOUR_WAY },
    { "Eight-Way Interleave", SMBIOS_MEMORY_CONTROLLER_INTERLEAVE_EIGHT_WAY },
    { "Sixteen-Way Interleave", SMBIOS_MEMORY_CONTROLLER_INTERLEAVE_SIXTEEN_WAY },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType5FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_ENUM(5, "Error Detecting Method", ErrorDetectingMethod, SmbiosType5ErrorDetectingMethodEnum),
    SMBIOS_DEFINE_FIELD_UINT(5, "Error Correcting Capability", ErrorCorrectingCapability.Value),
    SMBIOS_DEFINE_FIELD_BIT("Other", 0),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 1),
    SMBIOS_DEFINE_FIELD_BIT("None", 2),
    SMBIOS_DEFINE_FIELD_BIT("SingleBit", 3),
    SMBIOS_DEFINE_FIELD_BIT("DoubleBit", 4),
    SMBIOS_DEFINE_FIELD_BIT("Scrubbing", 5),
    SMBIOS_DEFINE_FIELD_ENUM(5, "Supported Interleave", SupportedInterleave, SmbiosType5InterleaveEnum),
    SMBIOS_DEFINE_FIELD_ENUM(5, "Current Interleave", CurrentInterleave, SmbiosType5InterleaveEnum),
    SMBIOS_DEFINE_FIELD_UINT(5, "Maximum Memory Module Size", MaximumMemoryModuleSize),
    SMBIOS_DEFINE_FIELD_UINT(5, "Supported Speeds", SupportedSpeeds.Value),
    SMBIOS_DEFINE_FIELD_BIT("Other", 0),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 1),
    SMBIOS_DEFINE_FIELD_BIT("70ns", 2),
    SMBIOS_DEFINE_FIELD_BIT("60ns", 3),
    SMBIOS_DEFINE_FIELD_BIT("50ns", 4),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 5, 11, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(5, "Supported Memory Types", SupportedMemoryTypes.Value),
    SMBIOS_MEMORY_TYPE_FIELDS,
    SMBIOS_DEFINE_FIELD_UINT(5, "Memory Module Voltage", MemoryModuleVoltage.Value),
    SMBIOS_DEFINE_FIELD_BIT("5V", 0),
    SMBIOS_DEFINE_FIELD_BIT("3.3V", 0),
    SMBIOS_DEFINE_FIELD_BIT("2.9V", 0),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 3, 5, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(5, "Number of Associated Memory Slots", NumberOfAssociatedMemorySlots),
};

#define SMBIOS_MEMORY_MODULE_SIZE_FIELDS\
    SMBIOS_DEFINE_BIT_FIELD("Size", 0, 7, SmbiosDataTypeUInt),\
    SMBIOS_DEFINE_FIELD_BIT("Double-bank", 7)

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType6FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(6, "Socket Designation", SocketDesignation),
    SMBIOS_DEFINE_FIELD_UINT(6, "Bank Connections", BankConnections),
    SMBIOS_DEFINE_FIELD_UINT(6, "Current Speed", CurrentSpeed),
    SMBIOS_DEFINE_FIELD_UINT(6, "Current Memory Type", CurrentMemoryType.Value),
    SMBIOS_MEMORY_TYPE_FIELDS,
    SMBIOS_DEFINE_FIELD_UINT(6, "Installed Size", InstalledSize.Value),
    SMBIOS_MEMORY_MODULE_SIZE_FIELDS,
    SMBIOS_DEFINE_FIELD_UINT(6, "Enabled Size", EnabledSize.Value),
    SMBIOS_MEMORY_MODULE_SIZE_FIELDS,
    SMBIOS_DEFINE_FIELD_UINT(6, "Error Status", ErrorStatus.Value),
    SMBIOS_DEFINE_FIELD_BIT("Uncorrectable errors received for the module", 0),
    SMBIOS_DEFINE_FIELD_BIT("Correctable errors received for the module", 1),
    SMBIOS_DEFINE_FIELD_BIT("Error Status information should be obtained from the event log", 2),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 3, 5, SmbiosDataTypeUInt),
};

#define SMBIOS_CACHE_SIZE_FIELDS\
    SMBIOS_DEFINE_BIT_FIELD("Size", 0, 15, SmbiosDataTypeUInt),\
    SMBIOS_DEFINE_FIELD_BIT("64K Granularity", 15)

#define SMBIOS_CACHE_SIZE2_FIELDS\
    SMBIOS_DEFINE_BIT_FIELD("Size", 0, 31, SmbiosDataTypeUInt),\
    SMBIOS_DEFINE_FIELD_BIT("64K Granularity", 31)

#define SMBIOS_CACHE_SRAM_TYPE_FIELDS\
    SMBIOS_DEFINE_FIELD_BIT("Other", 0),\
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 1),\
    SMBIOS_DEFINE_FIELD_BIT("Non-Burst", 2),\
    SMBIOS_DEFINE_FIELD_BIT("Burst", 3),\
    SMBIOS_DEFINE_FIELD_BIT("Pipeline Burst", 4),\
    SMBIOS_DEFINE_FIELD_BIT("Synchronous", 5),\
    SMBIOS_DEFINE_FIELD_BIT("Asynchronous", 6),\
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 7, 9, SmbiosDataTypeUInt)

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType7LocationEnum[] = {
    { "Internal", SMBIOS_CACHE_LOCATION_INTERNAL },
    { "External", SMBIOS_CACHE_LOCATION_EXTERNAL },
    { "Reserved", SMBIOS_CACHE_LOCATION_RESERVED },
    { "Unknown", SMBIOS_CACHE_LOCATION_UNKNOWN },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType7OperationalModeEnum[] = {
    { "Write Through", SMBIOS_CACHE_OPERATIONAL_MODE_WRITE_THROUGH },
    { "Write Back", SMBIOS_CACHE_OPERATIONAL_MODE_WRITE_BACK },
    { "Varies with Memory Address", SMBIOS_CACHE_OPERATIONAL_MODE_VARIES_WITH_MEMORY_ADDRESS },
    { "Unknown", SMBIOS_CACHE_OPERATIONAL_MODE_UNKNOWN },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType7ErrorCorrectionTypeEnum[] = {
    { "Other", SMBIOS_CACHE_ERROR_CORRECTION_TYPE_OTHER },
    { "Unknown", SMBIOS_CACHE_ERROR_CORRECTION_TYPE_UNKNOWN },
    { "None", SMBIOS_CACHE_ERROR_CORRECTION_TYPE_NONE },
    { "Parity", SMBIOS_CACHE_ERROR_CORRECTION_TYPE_PARITY },
    { "Single-bit ECC", SMBIOS_CACHE_ERROR_CORRECTION_TYPE_SINGLE_BIT_ECC },
    { "Multi-bit ECC", SMBIOS_CACHE_ERROR_CORRECTION_TYPE_MULTI_BIT_ECC },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType7SystemCacheTypeEnum[] = {
    { "Other", SMBIOS_CACHE_SYSTEM_CACHE_TYPE_OTHER },
    { "Unknown", SMBIOS_CACHE_SYSTEM_CACHE_TYPE_UNKNOWN },
    { "Instruction", SMBIOS_CACHE_SYSTEM_CACHE_TYPE_INSTRUCTION },
    { "Data", SMBIOS_CACHE_SYSTEM_CACHE_TYPE_DATA },
    { "Unified", SMBIOS_CACHE_SYSTEM_CACHE_TYPE_UNIFIED },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType7AssociativityEnum[] = {
    { "Other", SMBIOS_CACHE_ASSOCIATIVITY_OTHER },
    { "Unknown", SMBIOS_CACHE_ASSOCIATIVITY_UNKNOWN },
    { "Direct Mapped", SMBIOS_CACHE_ASSOCIATIVITY_DIRECT_MAPPED },
    { "2-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_2_WAY },
    { "4-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_4_WAY },
    { "Fully Associative", SMBIOS_CACHE_ASSOCIATIVITY_FULL },
    { "8-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_8_WAY },
    { "16-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_16_WAY },
    { "12-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_12_WAY },
    { "24-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_24_WAY },
    { "32-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_32_WAY },
    { "48-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_48_WAY },
    { "64-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_64_WAY },
    { "20-way Set-Associative", SMBIOS_CACHE_ASSOCIATIVITY_20_WAY },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType7FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(7, "Socket Designation", SocketDesignation),
    SMBIOS_DEFINE_FIELD_UINT(7, "Cache Configuration", Configuration.Value),
    SMBIOS_DEFINE_BIT_FIELD("Level", 0, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("Socketed", 3),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 4),
    SMBIOS_DEFINE_BIT_FIELD("Location", 5, 2, SmbiosDataTypeEnum, SMBIOS_FIELD_ENUM_VALUES(SmbiosType7LocationEnum)),
    SMBIOS_DEFINE_FIELD_BIT("Enabled", 7),
    SMBIOS_DEFINE_BIT_FIELD("Operational Mode", 8, 2, SmbiosDataTypeEnum, SMBIOS_FIELD_ENUM_VALUES(SmbiosType7LocationEnum)),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 10, 6, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(7, "Maximum Cache Size", MaximumCacheSize.Value),
    SMBIOS_CACHE_SIZE_FIELDS,
    SMBIOS_DEFINE_FIELD_UINT(7, "Installed Size", InstalledSize.Value),
    SMBIOS_CACHE_SIZE_FIELDS,
    SMBIOS_DEFINE_FIELD_UINT(7, "Supported SRAM Type", SupportedSRAMType.Value),
    SMBIOS_CACHE_SRAM_TYPE_FIELDS,
    SMBIOS_DEFINE_FIELD_UINT(7, "Current SRAM Type", CurrentSRAMType.Value),
    SMBIOS_CACHE_SRAM_TYPE_FIELDS,
    SMBIOS_DEFINE_FIELD_UINT(7, "Cache Speed", CacheSpeed),
    SMBIOS_DEFINE_FIELD_ENUM(7, "Error Correction Type", ErrorCorrectionType, SmbiosType7ErrorCorrectionTypeEnum),
    SMBIOS_DEFINE_FIELD_ENUM(7, "System Cache Type", SystemCacheType, SmbiosType7SystemCacheTypeEnum),
    SMBIOS_DEFINE_FIELD_ENUM(7, "Associativity", Associativity, SmbiosType7AssociativityEnum),
    SMBIOS_DEFINE_FIELD_UINT(7, "Maximum Cache Size 2", MaximumCacheSize2.Value),
    SMBIOS_CACHE_SIZE2_FIELDS,
    SMBIOS_DEFINE_FIELD_UINT(7, "Installed Cache Size 2", InstalledCacheSize2.Value),
    SMBIOS_CACHE_SIZE2_FIELDS,
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType8TypeEnum[] = {
    { "None", SMBIOS_PORT_CONNECTOR_TYPE_NONE },
    { "Centronics", SMBIOS_PORT_CONNECTOR_TYPE_CENTRONICS },
    { "Mini Centronics", SMBIOS_PORT_CONNECTOR_TYPE_MINI_CENTRONICS },
    { "Proprietary", SMBIOS_PORT_CONNECTOR_TYPE_MINI_PROPRIETARY },
    { "DB-25 pin male", SMBIOS_PORT_CONNECTOR_TYPE_DB_25_PIN_MALE },
    { "DB-25 pin female", SMBIOS_PORT_CONNECTOR_TYPE_DB_25_PIN_FEMALE },
    { "DB-15 pin male", SMBIOS_PORT_CONNECTOR_TYPE_DB_15_PIN_MALE },
    { "DB-15 pin female", SMBIOS_PORT_CONNECTOR_TYPE_DB_15_PIN_FEMALE },
    { "DB-9 pin male", SMBIOS_PORT_CONNECTOR_TYPE_DB_9_PIN_MALE },
    { "DB-9 pin female", SMBIOS_PORT_CONNECTOR_TYPE_DB_9_PIN_FEMALE },
    { "RJ-11", SMBIOS_PORT_CONNECTOR_TYPE_RJ_11 },
    { "RJ-45", SMBIOS_PORT_CONNECTOR_TYPE_RJ_45 },
    { "50-pin MiniSCSI", SMBIOS_PORT_CONNECTOR_TYPE_50_PIN_MINISCSI },
    { "Mini-DIN", SMBIOS_PORT_CONNECTOR_TYPE_MINI_DIN },
    { "Micro-DIN", SMBIOS_PORT_CONNECTOR_TYPE_MICRO_DIN },
    { "PS/2", SMBIOS_PORT_CONNECTOR_TYPE_PS_2 },
    { "Infrared", SMBIOS_PORT_CONNECTOR_TYPE_INFRARED },
    { "HP-HIL", SMBIOS_PORT_CONNECTOR_TYPE_HP_HIL },
    { "Access Bus (USB)", SMBIOS_PORT_CONNECTOR_TYPE_ACCESS_BUS },
    { "SSA SCSI", SMBIOS_PORT_CONNECTOR_TYPE_SSA_SCSI },
    { "Circular DIN-8 male", SMBIOS_PORT_CONNECTOR_TYPE_CIRCULAR_DIN_8_MALE },
    { "Circular DIN-8 female", SMBIOS_PORT_CONNECTOR_TYPE_CIRCULAR_DIN_8_FEMALE },
    { "On Board IDE", SMBIOS_PORT_CONNECTOR_TYPE_ON_BOARD_IDE },
    { "On Board Floppy", SMBIOS_PORT_CONNECTOR_TYPE_ON_BOARD_FLOPPY },
    { "9-pin Dual Inline (pin 10 cut)", SMBIOS_PORT_CONNECTOR_TYPE_9_PIN_DUAL_INLINE },
    { "25-pin Dual Inline (pin 26 cut)", SMBIOS_PORT_CONNECTOR_TYPE_25_PIN_DUAL_INLINE },
    { "50-pin Dual Inline", SMBIOS_PORT_CONNECTOR_TYPE_50_PIN_DUAL_INLINE },
    { "68-pin Dual Inline", SMBIOS_PORT_CONNECTOR_TYPE_68_PIN_DUAL_INLINE },
    { "On Board Sound Input from CD-ROM", SMBIOS_PORT_CONNECTOR_TYPE_ON_BOARD_SOUND_INPUT_FROM_CD_ROM },
    { "Mini-Centronics Type-14", SMBIOS_PORT_CONNECTOR_TYPE_MINI_CENTRONICS_TYPE_14 },
    { "Mini-Centronics Type-26", SMBIOS_PORT_CONNECTOR_TYPE_MINI_CENTRONICS_TYPE_26 },
    { "Mini-jack (headphones)", SMBIOS_PORT_CONNECTOR_TYPE_MINI_JACK },
    { "BNC", SMBIOS_PORT_CONNECTOR_TYPE_BNC },
    { "1394", SMBIOS_PORT_CONNECTOR_TYPE_1394 },
    { "SAS/SATA Plug Receptacle", SMBIOS_PORT_CONNECTOR_TYPE_SAS_SATA_PLUG_RECEPTACLE },
    { "USB Type-C Receptacle", SMBIOS_PORT_CONNECTOR_TYPE_USB_TYPE_C_RECEPTACLE },
    { "PC-98", SMBIOS_PORT_CONNECTOR_TYPE_PC_98 },
    { "PC-98Hireso", SMBIOS_PORT_CONNECTOR_TYPE_PC_98HIRESO },
    { "PC-H98", SMBIOS_PORT_CONNECTOR_TYPE_PC_H98 },
    { "PC-98Note", SMBIOS_PORT_CONNECTOR_TYPE_PC_98NOTE },
    { "PC-98Full", SMBIOS_PORT_CONNECTOR_TYPE_PC_98FULL },
    { "Other", SMBIOS_PORT_CONNECTOR_TYPE_OTHER },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType8PortTypeEnum[] = {
    { "None", SMBIOS_PORT_CONNECTOR_PORT_TYPE_NONE },
    { "Parallel Port XT/AT Compatible", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PARALLEL_PORT_XT_AT_COMPATIBLE },
    { "Parallel Port PS/2", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PARALLEL_PORT_PS_2 },
    { "Parallel Port ECP", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PARALLEL_PORT_ECP },
    { "Parallel Port EPP", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PARALLEL_PORT_EPP },
    { "Parallel Port ECP/EPP", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PARALLEL_PORT_ECP_EPP },
    { "Serial Port XT/AT Compatible", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SERIAL_PORT_XT_AT_COMPATIBLE },
    { "Serial Port 16450 Compatible", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SERIAL_PORT_16450_COMPATIBLE },
    { "Serial Port 16550 Compatible", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SERIAL_PORT_16550_COMPATIBLE },
    { "Serial Port 16550A Compatible", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SERIAL_PORT_16550A_COMPATIBLE },
    { "SCSI Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SCSI_PORT },
    { "MIDI Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_MIDI_PORT },
    { "Joy Stick Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_JOY_STICK_PORT },
    { "Keyboard Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_KEYBOARD_PORT },
    { "Mouse Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_MOUSE_PORT },
    { "SSA SCSI", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SSA_SCSI },
    { "USB", SMBIOS_PORT_CONNECTOR_PORT_TYPE_USB },
    { "FireWire (IEEE P1394)", SMBIOS_PORT_CONNECTOR_PORT_TYPE_FIRE_WIRE },
    { "PCMCIA Type I2", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PCMCIA_TYPE_I },
    { "PCMCIA Type II", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PCMCIA_TYPE_II },
    { "PCMCIA Type III", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PCMCIA_TYPE_III },
    { "Card bus", SMBIOS_PORT_CONNECTOR_PORT_TYPE_CARD_BUS },
    { "Access Bus Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_ACCESS_BUS_PORT },
    { "SCSI II", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SCSI_2 },
    { "SCSI Wide", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SCSI_WIDE },
    { "PC-98", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PC_98 },
    { "PC-98-Hireso", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PC_98_Hireso },
    { "PC-H98", SMBIOS_PORT_CONNECTOR_PORT_TYPE_PC_H98 },
    { "Video Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_VIDEO_PORT },
    { "Audio Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_AUDIO_PORT },
    { "Modem Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_MODEM_PORT },
    { "Network Port", SMBIOS_PORT_CONNECTOR_PORT_TYPE_NETWORK_PORT },
    { "SATA", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SATA },
    { "SAS", SMBIOS_PORT_CONNECTOR_PORT_TYPE_SAS },
    { "MFDP (Multi-Function Display Port)", SMBIOS_PORT_CONNECTOR_PORT_TYPE_MFDP },
    { "Thunderbolt", SMBIOS_PORT_CONNECTOR_PORT_TYPE_THUNDERBOLT },
    { "8251 Compatible", SMBIOS_PORT_CONNECTOR_PORT_TYPE_8251_COMPATIBLE },
    { "8251 FIFO Compatible", SMBIOS_PORT_CONNECTOR_PORT_TYPE_8251_FIFO_COMPATIBLE },
    { "Other", SMBIOS_PORT_CONNECTOR_PORT_TYPE_OTHER },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType8FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(8, "Internal Reference Designator", InternalReferenceDesignator),
    SMBIOS_DEFINE_FIELD_ENUM(8, "Internal Connector Type", InternalConnectorType, SmbiosType8TypeEnum),
    SMBIOS_DEFINE_FIELD_STRING(8, "External Reference Designator", ExternalReferenceDesignator),
    SMBIOS_DEFINE_FIELD_ENUM(8, "External Connector Type", ExternalConnectorType, SmbiosType8TypeEnum),
    SMBIOS_DEFINE_FIELD_ENUM(8, "Port Type", PortType, SmbiosType8PortTypeEnum),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType9TypeEnum[] = {
    { "Other", SMBIOS_SYSTEM_SLOTS_TYPE_OTHER },
    { "Unknown", SMBIOS_SYSTEM_SLOTS_TYPE_UNKNOWN },
    { "ISA", SMBIOS_SYSTEM_SLOTS_TYPE_ISA },
    { "MCA", SMBIOS_SYSTEM_SLOTS_TYPE_MCA },
    { "EISA", SMBIOS_SYSTEM_SLOTS_TYPE_EISA },
    { "PCI", SMBIOS_SYSTEM_SLOTS_TYPE_PCI },
    { "PC Card (PCMCIA)", SMBIOS_SYSTEM_SLOTS_TYPE_PC_CARD },
    { "VL-VESA", SMBIOS_SYSTEM_SLOTS_TYPE_VL_VESA },
    { "Proprietary", SMBIOS_SYSTEM_SLOTS_TYPE_PROPRIETARY },
    { "Processor Card Slot", SMBIOS_SYSTEM_SLOTS_TYPE_PROCESSOR_CARD_SLOT },
    { "Proprietary Memory Card Slot", SMBIOS_SYSTEM_SLOTS_TYPE_PROPRIETARY_MEMORY_CARD_SLOT },
    { "I/O Riser Card Slot", SMBIOS_SYSTEM_SLOTS_TYPE_IO_RISER_CARD_SLOT },
    { "NuBus", SMBIOS_SYSTEM_SLOTS_TYPE_NUBUS },
    { "PCI – 66MHz Capable", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_66MHZ_CAPABLE },
    { "AGP", SMBIOS_SYSTEM_SLOTS_TYPE_AGP },
    { "AGP 2X", SMBIOS_SYSTEM_SLOTS_TYPE_AGP_2X },
    { "AGP 4X", SMBIOS_SYSTEM_SLOTS_TYPE_AGP_4X },
    { "PCI-X", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_X },
    { "AGP 8X", SMBIOS_SYSTEM_SLOTS_TYPE_AGP_8X },
    { "M.2 Socket 1-DP (Mechanical Key A)", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_1_DP },
    { "M.2 Socket 1-SD (Mechanical Key E)", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_1_SD },
    { "M.2 Socket 2 (Mechanical Key B)", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_2 },
    { "M.2 Socket 3 (Mechanical Key M)", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_3 },
    { "MXM Type I", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_MXM_TYPE_I },
    { "MXM Type II", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_MXM_TYPE_II },
    { "MXM Type III (standard connector)", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_MXM_TYPE_III_STANDARD },
    { "MXM Type III (HE connector)", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_MXM_TYPE_III_HE },
    { "MXM Type IV", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_MXM_TYPE_IV },
    { "MXM 3.0 Type A", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_MXM_3_TYPE_A },
    { "MXM 3.0 Type B", SMBIOS_SYSTEM_SLOTS_TYPE_M2_SOCKET_MXM_3_TYPE_B },
    { "PCI Express Gen 2 SFF-8639 (U.2)", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_2_SFF_8639 },
    { "PCI Express Gen 3 SFF-8639 (U.2)", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_3_SFF_8639 },
    { "PCI Express Mini 52-pin (CEM spec. 2.0) with bottom-side keep-outs", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_MINI_52_PIN_WITH_BOTTOM_SIDE_KEEP_OUTS },
    { "PCI Express Mini 52-pin (CEM spec. 2.0) without bottom-side keep-outs", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_MINI_52_PIN_WITHOUT_BOTTOM_SIDE_KEEP_OUTS },
    { "PCI Express Mini 76-pin (CEM spec. 2.0)", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_MINI_76_PIN },
    { "PCI Express Gen 4 SFF-8639 (U.2)", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_4_SFF_8639 },
    { "PCI Express Gen 5 SFF-8639 (U.2)", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_5_SFF_8639 },
    { "OCP NIC 3.0 Small Form Factor (SFF)", SMBIOS_SYSTEM_SLOTS_TYPE_OCP_NIC_3_SFF },
    { "OCP NIC 3.0 Large Form Factor (LFF)", SMBIOS_SYSTEM_SLOTS_TYPE_OCP_NIC_3_LFF },
    { "OCP NIC Prior to 3.0", SMBIOS_SYSTEM_SLOTS_TYPE_OCP_NIC_PRIOR_TO_3 },
    { "CXL Flexbus 1.0 (deprecated)", SMBIOS_SYSTEM_SLOTS_TYPE_CXL_FLEXBUS_1 },
    { "PC-98/C20", SMBIOS_SYSTEM_SLOTS_TYPE_PC_98_C20 },
    { "PC-98/C24", SMBIOS_SYSTEM_SLOTS_TYPE_PC_98_C24 },
    { "PC-98/E", SMBIOS_SYSTEM_SLOTS_TYPE_PC_98_E },
    { "PC-98/Local Bus", SMBIOS_SYSTEM_SLOTS_TYPE_PC_98_LOCAL_BUS },
    { "PC-98/Card", SMBIOS_SYSTEM_SLOTS_TYPE_PC_98_CARD },
    { "PCI Express", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS },
    { "PCI Express x1", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_X1 },
    { "PCI Express x2", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_X2 },
    { "PCI Express x4", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_X4 },
    { "PCI Express x8", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_X8 },
    { "PCI Express x16", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_X16 },
    { "PCI Express Gen 2", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_2 },
    { "PCI Express Gen 2 x1", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_2_X1 },
    { "PCI Express Gen 2 x2", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_2_X2 },
    { "PCI Express Gen 2 x4", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_2_X4 },
    { "PCI Express Gen 2 x8", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_2_X8 },
    { "PCI Express Gen 2 x16", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_2_X16 },
    { "PCI Express Gen 3", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_3 },
    { "PCI Express Gen 3 x1", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_3_X1 },
    { "PCI Express Gen 3 x2", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_3_X2 },
    { "PCI Express Gen 3 x4", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_3_X4 },
    { "PCI Express Gen 3 x8", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_3_X8 },
    { "PCI Express Gen 3 x16", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_3_X16 },
    { "PCI Express Gen 4", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_4 },
    { "PCI Express Gen 4 x1", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_4_X1 },
    { "PCI Express Gen 4 x2", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_4_X2 },
    { "PCI Express Gen 4 x4", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_4_X4 },
    { "PCI Express Gen 4 x8", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_4_X8 },
    { "PCI Express Gen 4 x16", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_4_X16 },
    { "PCI Express Gen 5", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_5 },
    { "PCI Express Gen 5 x1", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_5_X1 },
    { "PCI Express Gen 5 x2", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_5_X2 },
    { "PCI Express Gen 5 x4", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_5_X4 },
    { "PCI Express Gen 5 x8", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_5_X8 },
    { "PCI Express Gen 5 x16", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_5_X16 },
    { "PCI Express Gen 6 and Beyond", SMBIOS_SYSTEM_SLOTS_TYPE_PCI_EXPRESS_GEN_6_AND_BEYOND },
    { "Enterprise and Datacenter 1U E1 Form Factor Slot", SMBIOS_SYSTEM_SLOTS_TYPE_EDSFF_E1S_E1L },
    { "Enterprise and Datacenter 3\" E3 Form Factor Slot", SMBIOS_SYSTEM_SLOTS_TYPE_EDSFF_E3S_E3L },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType9DataBusWidthEnum[] = {
    { "Other", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_OTHER },
    { "Unknown", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_UNKNOWN },
    { "8 bit", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_8_BIT },
    { "16 bit", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_16_BIT },
    { "32 bit", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_32_BIT },
    { "64 bit", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_64_BIT },
    { "128 bit", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_128_BIT },
    { "1x or x1", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_1X },
    { "2x or x2", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_2X },
    { "4x or x4", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_4X },
    { "8x or x8", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_8X },
    { "12x or x12", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_12X },
    { "16x or x16", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_16X },
    { "32x or x32", SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_32X },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType9CurrentUsageEnum[] = {
    { "Other", SMBIOS_SYSTEM_SLOTS_CURRENT_USAGE_OTHER },
    { "Unknown", SMBIOS_SYSTEM_SLOTS_CURRENT_USAGE_UNKNOWN },
    { "Available", SMBIOS_SYSTEM_SLOTS_CURRENT_USAGE_AVAILABLE },
    { "In use", SMBIOS_SYSTEM_SLOTS_CURRENT_USAGE_IN_USE },
    { "Unavailable", SMBIOS_SYSTEM_SLOTS_CURRENT_USAGE_UNAVAILABLE },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType9LengthEnum[] = {
    { "Other", SMBIOS_SYSTEM_SLOTS_LENGTH_OTHER },
    { "Unknown", SMBIOS_SYSTEM_SLOTS_LENGTH_UNKNOWN },
    { "Short Length", SMBIOS_SYSTEM_SLOTS_LENGTH_SHORT },
    { "Long Length", SMBIOS_SYSTEM_SLOTS_LENGTH_LONG },
    { "2.5\" drive form factor", SMBIOS_SYSTEM_SLOTS_LENGTH_2DOT5_INCH_DRIVE_FORM_FACTOR },
    { "3.5\" drive form factor", SMBIOS_SYSTEM_SLOTS_LENGTH_3DOT5_INCH_DRIVE_FORM_FACTOR },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType9FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(9, "Slot Designation", Designation),
    SMBIOS_DEFINE_FIELD_ENUM(9, "Slot Type", Type, SmbiosType9TypeEnum),
    SMBIOS_DEFINE_FIELD_ENUM(9, "Slot Data Bus Width", DataBusWidth, SmbiosType9DataBusWidthEnum),
    SMBIOS_DEFINE_FIELD_ENUM(9, "Current Usage", CurrentUsage, SmbiosType9CurrentUsageEnum),
    SMBIOS_DEFINE_FIELD_ENUM(9, "Slot Length", Length, SmbiosType9LengthEnum),
    SMBIOS_DEFINE_FIELD_UINT(9, "Slot ID", ID),
    SMBIOS_DEFINE_FIELD_UINT(9, "Slot Characteristics 1", Characteristics1.Value),
    SMBIOS_DEFINE_FIELD_BIT("Characteristics unknown", 0),
    SMBIOS_DEFINE_FIELD_BIT("Provides 5.0 volts", 1),
    SMBIOS_DEFINE_FIELD_BIT("Provides 3.3 volts", 2),
    SMBIOS_DEFINE_FIELD_BIT("Slot's opening is shared with another slot", 3),
    SMBIOS_DEFINE_FIELD_BIT("PC Card slot supports PC Card-16", 4),
    SMBIOS_DEFINE_FIELD_BIT("PC Card slot supports CardBus", 5),
    SMBIOS_DEFINE_FIELD_BIT("PC Card slot supports Zoom Video", 6),
    SMBIOS_DEFINE_FIELD_BIT("PC Card slot supports Modem Ring Resume", 7),
    SMBIOS_DEFINE_FIELD_UINT(9, "Slot Characteristics 2", Characteristics2.Value),
    SMBIOS_DEFINE_FIELD_BIT("PCI slot supports Power Management Event (PME#) signal", 0),
    SMBIOS_DEFINE_FIELD_BIT("Slot supports hot-plug devices", 1),
    SMBIOS_DEFINE_FIELD_BIT("PCI slot supports SMBus signal", 2),
    SMBIOS_DEFINE_FIELD_BIT("PCIe slot supports bifurcation", 3),
    SMBIOS_DEFINE_FIELD_BIT("Slot supports async/surprise removal", 4),
    SMBIOS_DEFINE_FIELD_BIT("Flexbus slot, CXL 1.0 capable", 5),
    SMBIOS_DEFINE_FIELD_BIT("Flexbus slot, CXL 2.0 capable", 6),
    SMBIOS_DEFINE_FIELD_BIT("Flexbus slot, CXL 3.0 capable", 7),
    SMBIOS_DEFINE_FIELD_UINT(9, "Segment Group Number (Base)", SegmentGroupNumber),
    SMBIOS_DEFINE_FIELD_UINT(9, "Bus Number (Base)", BusNumber),
    SMBIOS_DEFINE_FIELD_UINT(9, "Device/Function Number (Base)", DeviceFunctionNumber.Value),
    SMBIOS_DEFINE_BIT_FIELD("Function number", 0, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Device number", 3, 5, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(9, "Data Bus Width (Base)", BaseDataBusWidth),
    SMBIOS_DEFINE_FIELD_UINT(9, "Peer (S/B/D/F/Width) grouping count", PeerGroupingCount),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType10DeviceTypeEnum[] = {
    { "Other", SMBIOS_ONBOARD_DEVICES_TYPE_OTHER },
    { "Unknown", SMBIOS_ONBOARD_DEVICES_TYPE_UNKNOWN },
    { "Video", SMBIOS_ONBOARD_DEVICES_TYPE_VIDEO },
    { "SCSI Controller", SMBIOS_ONBOARD_DEVICES_TYPE_SCSI_CONTROLLER },
    { "Ethernet", SMBIOS_ONBOARD_DEVICES_TYPE_ETHERNET },
    { "Token Ring", SMBIOS_ONBOARD_DEVICES_TYPE_TOKEN_RING },
    { "Sound", SMBIOS_ONBOARD_DEVICES_TYPE_SOUND },
    { "PATA Controller", SMBIOS_ONBOARD_DEVICES_TYPE_PATA_CONTROLLER },
    { "SATA Controller", SMBIOS_ONBOARD_DEVICES_TYPE_SATA_CONTROLLER },
    { "SAS Controller", SMBIOS_ONBOARD_DEVICES_TYPE_SAS_CONTROLLER },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType10FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(10, "Type", Devices[0].Type.Value),
    SMBIOS_DEFINE_BIT_FIELD("Device Type", 0, 7, SmbiosDataTypeEnum, SMBIOS_FIELD_ENUM_VALUES(SmbiosType7LocationEnum)),
    SMBIOS_DEFINE_FIELD_BIT("Enabled", 7),
    SMBIOS_DEFINE_FIELD_STRING(10, "Description", Devices[0].Description),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType11FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(11, "Count", Count),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType12FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(12, "Count", Count),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType13FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(13, "Installable Languages", InstallableLanguages),
    SMBIOS_DEFINE_FIELD_UINT(13, "Flags", Flags.Value),
    SMBIOS_DEFINE_FIELD_BIT("Use the abbreviated format", 0),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 1, 7, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD(13, "Reserved", Reserved, SmbiosDataTypeOther),
    SMBIOS_DEFINE_FIELD_STRING(13, "Current Language", CurrentLanguage),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType14FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(14, "Group Name", GroupName),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType15AccessMethodEnum[] = {
    { "Indexed I/O: 1 8-bit index port, 1 8-bit data port", SMBIOS_SYSTEM_EVENT_LOG_ACCESSMETHOD_1_8BIT_INDEX_1_8BIT_DATA },
    { "Indexed I/O: 2 8-bit index port, 1 8-bit data port", SMBIOS_SYSTEM_EVENT_LOG_ACCESSMETHOD_2_8BIT_INDEX_1_8BIT_DATA },
    { "Indexed I/O: 1 16-bit index port, 1 8-bit data port", SMBIOS_SYSTEM_EVENT_LOG_ACCESSMETHOD_1_16BIT_INDEX_1_8BIT_DATA },
    { "Memory-mapped physical 32-bit address", SMBIOS_SYSTEM_EVENT_LOG_ACCESSMETHOD_MEMORY_MAPPED },
    { "Available through General-Purpose NonVolatile Data functions", SMBIOS_SYSTEM_EVENT_LOG_ACCESSMETHOD_NONVOLATILE_DATA },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType15HeaderFormatEnum[] = {
    { "No header", SMBIOS_SYSTEM_EVENT_LOG_HEADERFORMAT_NO_HEADER },
    { "Type 1 log header", SMBIOS_SYSTEM_EVENT_LOG_HEADERFORMAT_TYPE_1 },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType15FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(15, "Log Area Length", AreaLength),
    SMBIOS_DEFINE_FIELD_UINT(15, "Log Header Start Offset", HeaderStartOffset),
    SMBIOS_DEFINE_FIELD_UINT(15, "Log Data Start Offset", DataStartOffset),
    SMBIOS_DEFINE_FIELD_ENUM(15, "Access Method", AccessMethod, SmbiosType15AccessMethodEnum),
    SMBIOS_DEFINE_FIELD_UINT(15, "Log Status", Status.Value),
    SMBIOS_DEFINE_FIELD_BIT("Log area valid", 0),
    SMBIOS_DEFINE_FIELD_BIT("Log area full", 1),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 2, 6, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(15, "Log Change Token", ChangeToken),
    SMBIOS_DEFINE_FIELD_UINT(15, "Access Method Address", AccessMethodAddress),
    SMBIOS_DEFINE_FIELD_ENUM(15, "Log Header Format", HeaderFormat, SmbiosType15HeaderFormatEnum),
    SMBIOS_DEFINE_FIELD_UINT(15, "Number of Supported Log Type Descriptors", NumberOfSupportedTypeDescriptors),
    SMBIOS_DEFINE_FIELD_UINT(15, "Length of each Log Type Descriptor", LengthOfTypeDescriptor),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType16LocationEnum[] = {
    { "Other", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_OTHER },
    { "Unknown", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_UNKNOWN },
    { "System board or motherboard", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_SYSTEM_BOARD_OR_MOTHERBOARD },
    { "ISA add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_ISA_ADDON_CARD },
    { "EISA add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_EISA_ADDON_CARD },
    { "PCI add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_PCI_ADDON_CARD },
    { "MCA add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_MCA_ADDON_CARD },
    { "PCMCIA add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_PCMCIA_ADDON_CARD },
    { "Proprietary add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_PROPRIETARY_ADDON_CARD },
    { "NuBus", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_NUBUS },
    { "PC-98/C20 add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_PC_98_C20_ADDON_CARD },
    { "PC-98/C24 add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_PC_98_C24_ADDON_CARD },
    { "PC-98/E add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_PC_98_E_ADDON_CARD },
    { "PC-98/Local bus add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_PC_98_LOCAL_BUS_ADDON_CARD },
    { "CXL add-on card", SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_CXL_ADDON_CARD },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType16UseEnum[] = {
    { "Other", SMBIOS_PHYSICAL_MEMORY_ARRAY_USE_OTHER },
    { "Unknown", SMBIOS_PHYSICAL_MEMORY_ARRAY_USE_UNKNOWN },
    { "System memory", SMBIOS_PHYSICAL_MEMORY_ARRAY_USE_SYSTEM_MEMORY },
    { "Video memory", SMBIOS_PHYSICAL_MEMORY_ARRAY_USE_VIDEO_MEMORY },
    { "Flash memory", SMBIOS_PHYSICAL_MEMORY_ARRAY_USE_FLASH_MEMORY },
    { "Non-volatile RAM", SMBIOS_PHYSICAL_MEMORY_ARRAY_USE_NON_VOLATILE_RAM },
    { "Cache memory", SMBIOS_PHYSICAL_MEMORY_ARRAY_USE_CACHE_MEMORY },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType16ErrorCorrectionEnum[] = {
    { "Other", SMBIOS_PHYSICAL_MEMORY_ARRAY_ERROR_CORRECTION_TYPE_OTHER },
    { "Unknown", SMBIOS_PHYSICAL_MEMORY_ARRAY_ERROR_CORRECTION_TYPE_UNKNOWN },
    { "None", SMBIOS_PHYSICAL_MEMORY_ARRAY_ERROR_CORRECTION_TYPE_NONE },
    { "Parity", SMBIOS_PHYSICAL_MEMORY_ARRAY_ERROR_CORRECTION_TYPE_PARITY },
    { "Single-bit ECC", SMBIOS_PHYSICAL_MEMORY_ARRAY_ERROR_CORRECTION_TYPE_SINGLE_BIT_ECC },
    { "Multi-bit ECC", SMBIOS_PHYSICAL_MEMORY_ARRAY_ERROR_CORRECTION_TYPE_MULTI_BIT_ECC },
    { "CRC", SMBIOS_PHYSICAL_MEMORY_ARRAY_ERROR_CORRECTION_TYPE_CRC },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType16FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_ENUM(16, "Location", Location, SmbiosType16LocationEnum),
    SMBIOS_DEFINE_FIELD_ENUM(16, "Use", Use, SmbiosType16UseEnum),
    SMBIOS_DEFINE_FIELD_ENUM(16, "Memory Error Correction", ErrorCorrection, SmbiosType16ErrorCorrectionEnum),
    SMBIOS_DEFINE_FIELD_UINT(16, "Maximum Capacity", MaximumCapacity),
    SMBIOS_DEFINE_FIELD_UINT(16, "Memory Error Information Handle", ErrorInformationHandle),
    SMBIOS_DEFINE_FIELD_UINT(16, "Number of Memory Devices", NumberOfMemoryDevices),
    SMBIOS_DEFINE_FIELD_UINT(16, "Extended Maximum Capacity", ExtendedMaximumCapacity),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType17FormFactorEnum[] = {
    { "Other", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_OTHER },
    { "Unknown", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_UNKNOWN },
    { "SIMM", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_SIMM },
    { "SIP", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_SIP },
    { "Chip", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_CHIP },
    { "DIP", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_DIP },
    { "ZIP", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_ZIP },
    { "Proprietary Card", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_PROPRIETARY_CARD },
    { "DIMM", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_DIMM },
    { "TSOP", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_TSOP },
    { "Row of chips", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_ROW_OF_CHIPS },
    { "RIMM", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_RIMM },
    { "SODIMM", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_SODIMM },
    { "SRIMM", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_SRIMM },
    { "FB-DIMM", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_FB_DIMM },
    { "Die", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_DIE },
    { "CAMM", SMBIOS_MEMORY_DEVICE_FORM_FACTOR_CAMM },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType17TypeEnum[] = {
    { "Other", SMBIOS_MEMORY_DEVICE_TYPE_OTHER },
    { "Unknown", SMBIOS_MEMORY_DEVICE_TYPE_UNKNOWN },
    { "DRAM", SMBIOS_MEMORY_DEVICE_TYPE_DRAM },
    { "EDRAM", SMBIOS_MEMORY_DEVICE_TYPE_EDRAM },
    { "VRAM", SMBIOS_MEMORY_DEVICE_TYPE_VRAM },
    { "SRAM", SMBIOS_MEMORY_DEVICE_TYPE_SRAM },
    { "RAM", SMBIOS_MEMORY_DEVICE_TYPE_RAM },
    { "ROM", SMBIOS_MEMORY_DEVICE_TYPE_ROM },
    { "FLASH", SMBIOS_MEMORY_DEVICE_TYPE_FLASH },
    { "EEPROM", SMBIOS_MEMORY_DEVICE_TYPE_EEPROM },
    { "FEPROM", SMBIOS_MEMORY_DEVICE_TYPE_FEPROM },
    { "EPROM", SMBIOS_MEMORY_DEVICE_TYPE_EPROM },
    { "CDRAM", SMBIOS_MEMORY_DEVICE_TYPE_CDRAM },
    { "3DRAM", SMBIOS_MEMORY_DEVICE_TYPE_3DRAM },
    { "SDRAM", SMBIOS_MEMORY_DEVICE_TYPE_SDRAM },
    { "SGRAM", SMBIOS_MEMORY_DEVICE_TYPE_SGRAM },
    { "RDRAM", SMBIOS_MEMORY_DEVICE_TYPE_RDRAM },
    { "DDR", SMBIOS_MEMORY_DEVICE_TYPE_DDR },
    { "DDR2", SMBIOS_MEMORY_DEVICE_TYPE_DDR2 },
    { "DDR2 FB-DIMM", SMBIOS_MEMORY_DEVICE_TYPE_DDR2_FB_DIMM },
    { "DDR3", SMBIOS_MEMORY_DEVICE_TYPE_DDR3 },
    { "FBD2", SMBIOS_MEMORY_DEVICE_TYPE_FBD2 },
    { "DDR4", SMBIOS_MEMORY_DEVICE_TYPE_DDR4 },
    { "LPDDR", SMBIOS_MEMORY_DEVICE_TYPE_LPDDR },
    { "LPDDR2", SMBIOS_MEMORY_DEVICE_TYPE_LPDDR2 },
    { "LPDDR3", SMBIOS_MEMORY_DEVICE_TYPE_LPDDR3 },
    { "LPDDR4", SMBIOS_MEMORY_DEVICE_TYPE_LPDDR4 },
    { "Logical non-volatile device", SMBIOS_MEMORY_DEVICE_TYPE_LOGICAL_NON_VOLATILE_DEVICE },
    { "HBM (High Bandwidth Memory)", SMBIOS_MEMORY_DEVICE_TYPE_HBM },
    { "HBM2 (High Bandwidth Memory Generation 2)", SMBIOS_MEMORY_DEVICE_TYPE_HBM2 },
    { "DDR5", SMBIOS_MEMORY_DEVICE_TYPE_DDR5 },
    { "LPDDR5", SMBIOS_MEMORY_DEVICE_TYPE_LPDDR5 },
    { "HBM3 (High Bandwidth Memory Generation 3)", SMBIOS_MEMORY_DEVICE_TYPE_HBM3 },
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosType17TechnologyEnum[] = {
    { u8"Other", SMBIOS_MEMORY_DEVICE_TECHNOLOGY_OTHER },
    { u8"Unknown", SMBIOS_MEMORY_DEVICE_TECHNOLOGY_UNKNOWN },
    { u8"DRAM", SMBIOS_MEMORY_DEVICE_TECHNOLOGY_DRAM },
    { u8"NVDIMM-N", SMBIOS_MEMORY_DEVICE_TECHNOLOGY_NVDIMM_N },
    { u8"NVDIMM-F", SMBIOS_MEMORY_DEVICE_TECHNOLOGY_NVDIMM_F },
    { u8"NVDIMM-P", SMBIOS_MEMORY_DEVICE_TECHNOLOGY_NVDIMM_P },
    { u8"Intel® Optane™ persistent memory", SMBIOS_MEMORY_DEVICE_TECHNOLOGY_INTEL_OPTANE_PERSISTENT_MEMORY },
    { u8"MRDIMM", SMBIOS_MEMORY_DEVICE_TECHNOLOGY_MRDIMM },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType17FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(17, "Physical Memory Array Handle", PhysicalMemoryArrayHandle),
    SMBIOS_DEFINE_FIELD_UINT(17, "Memory Error Information Handle", ErrorInformationHandle),
    SMBIOS_DEFINE_FIELD_UINT(17, "Total Width", TotalWidth),
    SMBIOS_DEFINE_FIELD_UINT(17, "Data Width", DataWidth),
    SMBIOS_DEFINE_FIELD_UINT(17, "Size", Size.Value),
    SMBIOS_DEFINE_BIT_FIELD("Size", 0, 15, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("Granularity in KB", 15),
    SMBIOS_DEFINE_FIELD_ENUM(17, "Form Factor", FormFactor, SmbiosType17FormFactorEnum),
    SMBIOS_DEFINE_FIELD_UINT(17, "Device Set", DeviceSet),
    SMBIOS_DEFINE_FIELD_STRING(17, "Device Locator", DeviceLocator),
    SMBIOS_DEFINE_FIELD_STRING(17, "Bank Locator", BankLocator),
    SMBIOS_DEFINE_FIELD_ENUM(17, "Memory Type", Type, SmbiosType17TypeEnum),
    SMBIOS_DEFINE_FIELD_UINT(17, "Type Detail", TypeDetail.Value),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 0),
    SMBIOS_DEFINE_FIELD_BIT("Other", 1),
    SMBIOS_DEFINE_FIELD_BIT("Unknow", 2),
    SMBIOS_DEFINE_FIELD_BIT("Fast-paged", 3),
    SMBIOS_DEFINE_FIELD_BIT("Static column", 4),
    SMBIOS_DEFINE_FIELD_BIT("Pseudo-static", 5),
    SMBIOS_DEFINE_FIELD_BIT("RAMBUS", 6),
    SMBIOS_DEFINE_FIELD_BIT("Synchronous", 7),
    SMBIOS_DEFINE_FIELD_BIT("CMOS", 8),
    SMBIOS_DEFINE_FIELD_BIT("EDO", 9),
    SMBIOS_DEFINE_FIELD_BIT("Window DRAM", 10),
    SMBIOS_DEFINE_FIELD_BIT("Cache DRAM", 11),
    SMBIOS_DEFINE_FIELD_BIT("Non-volatile", 12),
    SMBIOS_DEFINE_FIELD_BIT("Registered (Buffered)", 13),
    SMBIOS_DEFINE_FIELD_BIT("Unbuffered (Unregistered)", 14),
    SMBIOS_DEFINE_FIELD_BIT("LRDIMM", 15),
    SMBIOS_DEFINE_FIELD_UINT(17, "Speed", Speed),
    SMBIOS_DEFINE_FIELD_STRING(17, "Manufacturer", Manufacturer),
    SMBIOS_DEFINE_FIELD_STRING(17, "Serial Number", SerialNumber),
    SMBIOS_DEFINE_FIELD_STRING(17, "Asset Tag", AssetTag),
    SMBIOS_DEFINE_FIELD_STRING(17, "Part Number", PartNumber),
    SMBIOS_DEFINE_FIELD_UINT(17, "Attributes", Attributes.Value),
    SMBIOS_DEFINE_BIT_FIELD("Rank", 0, 4, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 4, 4, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(17, "Extended Size", ExtendedSize.Value),
    SMBIOS_DEFINE_BIT_FIELD("Size in MB", 0, 31, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 15),
    SMBIOS_DEFINE_FIELD_UINT(17, "Configured Memory Speed", ConfiguredMemorySpeed),
    SMBIOS_DEFINE_FIELD_UINT(17, "Minimum voltage", MinimumVoltage),
    SMBIOS_DEFINE_FIELD_UINT(17, "Maximum voltage", MaximumVoltage),
    SMBIOS_DEFINE_FIELD_UINT(17, "Configured voltage", ConfiguredVoltage),
    SMBIOS_DEFINE_FIELD_ENUM(17, "Memory Technology", Technology, SmbiosType17TechnologyEnum),
    SMBIOS_DEFINE_FIELD_UINT(17, "Memory Operating Mode Capability", OperatingModeCapability),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 0),
    SMBIOS_DEFINE_FIELD_BIT("Other", 1),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 2),
    SMBIOS_DEFINE_FIELD_BIT("Volatile memory", 3),
    SMBIOS_DEFINE_FIELD_BIT("Byte-accessible persistent memory", 4),
    SMBIOS_DEFINE_FIELD_BIT("Block-accessible persistent memory", 5),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 6, 10, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_STRING(17, "Firmware Version", FirmwareVersion),
    SMBIOS_DEFINE_FIELD_UINT(17, "Module Manufacturer ID", ModuleManufacturerID),
    SMBIOS_DEFINE_FIELD_UINT(17, "Module Product ID", ModuleProductID),
    SMBIOS_DEFINE_FIELD_UINT(17, "Memory Subsystem Controller Manufacturer ID", SubsystemControllerManufacturerID),
    SMBIOS_DEFINE_FIELD_UINT(17, "Memory Subsystem Controller Product ID", SubsystemControllerProductID),
    SMBIOS_DEFINE_FIELD_UINT(17, "Non-volatile Size", NonVolatileSize),
    SMBIOS_DEFINE_FIELD_UINT(17, "Volatile Size", VolatileSize),
    SMBIOS_DEFINE_FIELD_UINT(17, "Cache Size", CacheSize),
    SMBIOS_DEFINE_FIELD_UINT(17, "Logical Size", LogicalSize),
    SMBIOS_DEFINE_FIELD_UINT(17, "Extended Speed", ExtendedSpeed),
    SMBIOS_DEFINE_FIELD_UINT(17, "Extended Configured Memory Speed", ExtendedConfiguredSpeed),
    SMBIOS_DEFINE_FIELD_UINT(17, "PMIC0 Manufacturer ID", PMIC0ManufacturerID),
    SMBIOS_DEFINE_FIELD_UINT(17, "PMIC0 Revision Number", PMIC0RevisionNumber),
    SMBIOS_DEFINE_FIELD_UINT(17, "RCD Manufacturer ID", RCDManufacturerID),
    SMBIOS_DEFINE_FIELD_UINT(17, "RCD Revision Number", RCDRevisionNumber),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType18FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_ENUM(18, "Error Type", Type, SmbiosMemoryErrorTypeEnum),
    SMBIOS_DEFINE_FIELD_ENUM(18, "Error Granularity", Granularity, SmbiosMemoryErrorGranularityEnum),
    SMBIOS_DEFINE_FIELD_ENUM(18, "Error Operation", Operation, SmbiosMemoryErrorOperationEnum),
    SMBIOS_DEFINE_FIELD_UINT(18, "Vendor Syndrome", VendorSyndrome),
    SMBIOS_DEFINE_FIELD_UINT(18, "Memory Array Error Address", MemoryArrayErrorAddress),
    SMBIOS_DEFINE_FIELD_UINT(18, "Device Error Address", DeviceErrorAddress),
    SMBIOS_DEFINE_FIELD_UINT(18, "Error Resolution", Resolution),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType19FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(19, "Starting Address", StartingAddress),
    SMBIOS_DEFINE_FIELD_UINT(19, "Ending Address", EndingAddress),
    SMBIOS_DEFINE_FIELD_UINT(19, "Memory Array Handle", MemoryArrayHandle),
    SMBIOS_DEFINE_FIELD_UINT(19, "Partition Width", PartitionWidth),
    SMBIOS_DEFINE_FIELD_UINT(19, "Extended Starting Address", ExtendedStartingAddress),
    SMBIOS_DEFINE_FIELD_UINT(19, "Extended Ending Address", ExtendedEndingAddress),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType20FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(20, "Starting Address", StartingAddress),
    SMBIOS_DEFINE_FIELD_UINT(20, "Ending Address", EndingAddress),
    SMBIOS_DEFINE_FIELD_UINT(20, "Memory Device Handle", MemoryDeviceHandle),
    SMBIOS_DEFINE_FIELD_UINT(20, "Memory Array Mapped Address Handle", MemoryArrayMappedAddressHandle),
    SMBIOS_DEFINE_FIELD_UINT(20, "Partition Row Position", PartitionRowPosition),
    SMBIOS_DEFINE_FIELD_UINT(20, "Interleave Position", InterleavePosition),
    SMBIOS_DEFINE_FIELD_UINT(20, "Interleaved Data Depth", InterleavedDataDepth),
    SMBIOS_DEFINE_FIELD_UINT(20, "Extended Starting Address", ExtendedStartingAddress),
    SMBIOS_DEFINE_FIELD_UINT(20, "Extended Ending Address", ExtendedEndingAddress),
};

__declspec(selectany)
SMBIOS_TYPE_INFO SmbiosTypeInfo[] = {
    SMBIOS_DEFINE_TYPE(0, "Platform Firmware Information"),
    SMBIOS_DEFINE_TYPE(1, "System Information"),
    SMBIOS_DEFINE_TYPE(2, "Baseboard Information"),
    SMBIOS_DEFINE_TYPE(3, "System Enclosure or Chassis"),
    SMBIOS_DEFINE_TYPE(4, "Processor Information"),
    SMBIOS_DEFINE_TYPE(5, "Memory Controller Information (Obsolete)"),
    SMBIOS_DEFINE_TYPE(6, "Memory Module Information (Obsolete)"),
    SMBIOS_DEFINE_TYPE(7, "Cache Information"),
    SMBIOS_DEFINE_TYPE(8, "Port Connector Information"),
    SMBIOS_DEFINE_TYPE(9, "System Slots"),
    SMBIOS_DEFINE_TYPE(10, "On Board Devices Information (Obsolete)"), // TODO
    SMBIOS_DEFINE_TYPE(11, "OEM Strings"), // TODO
    SMBIOS_DEFINE_TYPE(12, "System Configuration Options"), // TODO
    SMBIOS_DEFINE_TYPE(13, "Firmware Language Information"), // TODO
    SMBIOS_DEFINE_TYPE(14, "Group Associations"),
    SMBIOS_DEFINE_TYPE(15, "System Event Log"),
    SMBIOS_DEFINE_TYPE(16, "Physical Memory Array"),
    SMBIOS_DEFINE_TYPE(17, "Memory Device"),
    SMBIOS_DEFINE_TYPE(18, "32-Bit Memory Error Information"),
    SMBIOS_DEFINE_TYPE(19, "Memory Array Mapped Address"),
    SMBIOS_DEFINE_TYPE(20, "Memory Device Mapped Address"),
    { 21, "Built-in Pointing Device", 0, (void*)0 },
    { 22, "Portable Battery", 0, (void*)0 },
    { 23, "System Reset", 0, (void*)0 },
    { 24, "Hardware Security", 0, (void*)0 },
    { 25, "System Power Controls", 0, (void*)0 },
    { 26, "Voltage Probe", 0, (void*)0 },
    { 27, "Cooling Device", 0, (void*)0 },
    { 28, "Temperature Probe", 0, (void*)0 },
    { 29, "Electrical Current Probe", 0, (void*)0 },
    { 30, "Out-of-Band Remote Access", 0, (void*)0 },
    { 31, "Boot Integrity Services (BIS) Entry Point", 0, (void*)0 },
    { 32, "System Boot Information", 0, (void*)0 },
    { 33, "64-Bit Memory Error Information", 0, (void*)0 },
    { 34, "Management Device", 0, (void*)0 },
    { 35, "Management Device Component", 0, (void*)0 },
    { 36, "Management Device Threshold Data", 0, (void*)0 },
    { 37, "Memory Channel", 0, (void*)0 },
    { 38, "IPMI Device Information", 0, (void*)0 },
    { 39, "System Power Supply", 0, (void*)0 },
    { 40, "Additional Information", 0, (void*)0 },
    { 41, "Onboard Devices Extended Information", 0, (void*)0 },
    { 42, "Management Controller Host Interface", 0, (void*)0 },
    { 43, "TPM Device", 0, (void*)0 },
    { 44, "Processor Additional Information", 0, (void*)0 },
    { 45, "Firmware Inventory Information", 0, (void*)0 },
    { 46, "String Property", 0, (void*)0 },
    { 126, "Inactive", 0, (void*)0 },
    { 127, "End-of-Table", 0, (void*)0 },
};
