//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by TypeInfoGenerator in KNSoft.SMBIOS project
//     https://github.com/KNSoft/KNSoft.SMBIOS
//     Do not change this file manually
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "SMBIOS.h"
#include "SMBIOS.TypeInfo.inl"

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosPlatformFirmwareExtendedRomsizeUnitEnum[] = {
    { u8"MB", SMBIOS_PLATFORM_FIRMWARE_EXTENDED_ROMSIZE_UNIT_MB },
    { u8"GB", SMBIOS_PLATFORM_FIRMWARE_EXTENDED_ROMSIZE_UNIT_GB },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType0FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(0, "Vendor", Vendor),
    SMBIOS_DEFINE_FIELD_STRING(0, "Firmware Version", Version),
    SMBIOS_DEFINE_FIELD_UINT(0, "BIOS Starting Address Segment", BIOSStartingAddressSegment),
    SMBIOS_DEFINE_FIELD_STRING(0, "Firmware Release Date", ReleaseDate),
    SMBIOS_DEFINE_FIELD_UINT(0, "Firmware ROM Size", ROMSize),
    SMBIOS_DEFINE_FIELD_UINT(0, "Firmware Characteristics", Characteristics.Value),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 0),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 1),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 2),
    SMBIOS_DEFINE_FIELD_BIT("Firmware Characteristics are not supported", 3),
    SMBIOS_DEFINE_FIELD_BIT("ISA is supported", 4),
    SMBIOS_DEFINE_FIELD_BIT("MCA is supported", 5),
    SMBIOS_DEFINE_FIELD_BIT("EISA is supported", 6),
    SMBIOS_DEFINE_FIELD_BIT("PCI is supported", 7),
    SMBIOS_DEFINE_FIELD_BIT("PC card (PCMCIA) is supported", 8),
    SMBIOS_DEFINE_FIELD_BIT("Plug and Play is supported", 9),
    SMBIOS_DEFINE_FIELD_BIT("APM is supported", 10),
    SMBIOS_DEFINE_FIELD_BIT("Firmware is upgradeable (Flash)", 11),
    SMBIOS_DEFINE_FIELD_BIT("Firmware shadowing is allowed", 12),
    SMBIOS_DEFINE_FIELD_BIT("VL-VESA is supported", 13),
    SMBIOS_DEFINE_FIELD_BIT("ESCD support is available", 14),
    SMBIOS_DEFINE_FIELD_BIT("Boot from CD is supported", 15),
    SMBIOS_DEFINE_FIELD_BIT("Selectable boot is supported", 16),
    SMBIOS_DEFINE_FIELD_BIT("Firmware ROM is socketed (e.g., PLCC or SOP socket)", 17),
    SMBIOS_DEFINE_FIELD_BIT("Boot from PC card (PCMCIA) is supported", 18),
    SMBIOS_DEFINE_FIELD_BIT("EDD specification is supported", 19),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — Japanese floppy for NEC 9800 1.2 MB (3.5\", 1K bytes/sector, 360 RPM) is supported", 20),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — Japanese floppy for Toshiba 1.2 MB (3.5\", 360 RPM) is supported", 21),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — 5.25\" / 360 KB floppy services are supported", 22),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — 5.25\" / 1.2 MB floppy services are supported", 23),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — 3.5\" / 720 KB floppy services are supported", 24),
    SMBIOS_DEFINE_FIELD_BIT("Int 13h — 3.5\" / 2.88 MB floppy services are supported", 25),
    SMBIOS_DEFINE_FIELD_BIT("Int 5h, print screen service is supported", 26),
    SMBIOS_DEFINE_FIELD_BIT("Int 9h, 8042 keyboard services are supported", 27),
    SMBIOS_DEFINE_FIELD_BIT("Int 14h, serial services are supported", 28),
    SMBIOS_DEFINE_FIELD_BIT("Int 17h, printer services are supported", 29),
    SMBIOS_DEFINE_FIELD_BIT("Int 10h, CGA/Mono Video Services are supported", 30),
    SMBIOS_DEFINE_FIELD_BIT("NEC PC-98", 31),
    SMBIOS_DEFINE_BIT_FIELD("Reserved for platform firmware vendor", 32, 16, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Reserved for system vendor", 48, 16, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(0, "Firmware Characteristics Extension Byte 1", CharacteristicsExtensionByte1.Value),
    SMBIOS_DEFINE_FIELD_BIT("ACPI is supported", 0),
    SMBIOS_DEFINE_FIELD_BIT("USB Legacy is supported", 1),
    SMBIOS_DEFINE_FIELD_BIT("AGP is supported", 2),
    SMBIOS_DEFINE_FIELD_BIT("I2O boot is supported", 3),
    SMBIOS_DEFINE_FIELD_BIT("LS-120 SuperDisk boot is supported", 4),
    SMBIOS_DEFINE_FIELD_BIT("ATAPI ZIP drive boot is supported", 5),
    SMBIOS_DEFINE_FIELD_BIT("1394 boot is supported", 6),
    SMBIOS_DEFINE_FIELD_BIT("Smart battery is supported", 7),
    SMBIOS_DEFINE_FIELD_UINT(0, "Firmware Characteristics Extension Byte 2", CharacteristicsExtensionByte2.Value),
    SMBIOS_DEFINE_FIELD_BIT("BIOS Boot Specification is supported", 0),
    SMBIOS_DEFINE_FIELD_BIT("Function key-initiated network service boot is supported", 1),
    SMBIOS_DEFINE_FIELD_BIT("Enable targeted content distribution", 2),
    SMBIOS_DEFINE_FIELD_BIT("UEFI Specification is supported", 3),
    SMBIOS_DEFINE_FIELD_BIT("SMBIOS table describes a virtual machine", 4),
    SMBIOS_DEFINE_FIELD_BIT("Manufacturing mode is supported", 5),
    SMBIOS_DEFINE_FIELD_BIT("Manufacturing mode is enabled", 6),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 7),
    SMBIOS_DEFINE_FIELD_UINT(0, "Platform Firmware Major Release", MajorRelease),
    SMBIOS_DEFINE_FIELD_UINT(0, "Platform Firmware Minor Release", MinorRelease),
    SMBIOS_DEFINE_FIELD_UINT(0, "Embedded Controller Firmware Major Release", ECFirmwareMajorRelease),
    SMBIOS_DEFINE_FIELD_UINT(0, "Embedded Controller Firmware Minor Release", ECFirmwareMinorRelease),
    SMBIOS_DEFINE_FIELD_UINT(0, "Extended Firmware ROM Size", ExtendedROMSize.Value),
    SMBIOS_DEFINE_BIT_FIELD("Size", 0, 14, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Unit", 14, 2, SmbiosDataTypeEnum, SMBIOS_FIELD_ENUM_VALUES(SmbiosPlatformFirmwareExtendedRomsizeUnitEnum)),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosSystemWakeuptypeEnum[] = {
    { u8"Reserved", SMBIOS_SYSTEM_WAKEUPTYPE_RESERVED },
    { u8"Other", SMBIOS_SYSTEM_WAKEUPTYPE_OTHER },
    { u8"Unknown", SMBIOS_SYSTEM_WAKEUPTYPE_UNKNOW },
    { u8"APM Timer", SMBIOS_SYSTEM_WAKEUPTYPE_APM_TIMER },
    { u8"Modem Ring", SMBIOS_SYSTEM_WAKEUPTYPE_MODEM_RING },
    { u8"LAN Remote", SMBIOS_SYSTEM_WAKEUPTYPE_LAN_REMOTE },
    { u8"Power Switch", SMBIOS_SYSTEM_WAKEUPTYPE_POWER_SWITCH },
    { u8"PCI PME#", SMBIOS_SYSTEM_WAKEUPTYPE_PCI_PME },
    { u8"AC Power Restored", SMBIOS_SYSTEM_WAKEUPTYPE_AC_POWER_RESTORED },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType1FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(1, "Manufacturer", Manufacturer),
    SMBIOS_DEFINE_FIELD_STRING(1, "Product Name", ProductName),
    SMBIOS_DEFINE_FIELD_STRING(1, "Version", Version),
    SMBIOS_DEFINE_FIELD_STRING(1, "Serial Number", SerialNumber),
    SMBIOS_DEFINE_FIELD(1, "UUID", UUID, SmbiosDataTypeUuid),
    SMBIOS_DEFINE_FIELD_ENUM(1, "Wake-up Type", WakeUpType, SmbiosSystemWakeuptypeEnum),
    SMBIOS_DEFINE_FIELD_STRING(1, "SKU Number", SKUNumber),
    SMBIOS_DEFINE_FIELD_STRING(1, "Family", Family),
};

__declspec(selectany)
SMBIOS_FIELD_ENUM SmbiosBaseboardTypeEnum[] = {
    { u8"Unknown", SMBIOS_BASEBOARD_TYPE_UNKNOWN },
    { u8"Other", SMBIOS_BASEBOARD_TYPE_OTHER },
    { u8"Server Blade", SMBIOS_BASEBOARD_TYPE_SERVER_BLADE },
    { u8"Connectivity Switch", SMBIOS_BASEBOARD_TYPE_CONNECTIVITY_SWITCH },
    { u8"System Management Module", SMBIOS_BASEBOARD_TYPE_SYSTEM_MANAGEMENT_MODULE },
    { u8"Processor Module", SMBIOS_BASEBOARD_TYPE_PROCESSOR_MODULE },
    { u8"I/O Module", SMBIOS_BASEBOARD_TYPE_IO_MODULE },
    { u8"Memory Module", SMBIOS_BASEBOARD_TYPE_MEMORY_MODULE },
    { u8"Daughter board", SMBIOS_BASEBOARD_TYPE_DAUGHTER_BOARD },
    { u8"Motherboard (includes processor, memory, and I/O)", SMBIOS_BASEBOARD_TYPE_MOTHERBOARD },
    { u8"Processor/Memory Module", SMBIOS_BASEBOARD_TYPE_PROCESSOR_MEMORY_MODULE },
    { u8"Processor/IO Module", SMBIOS_BASEBOARD_TYPE_PROCESSOR_IO_MODULE },
    { u8"Interconnect board", SMBIOS_BASEBOARD_TYPE_INTERCONNECT_BOARD },
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType2FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_STRING(2, "Manufacturer", Manufacturer),
    SMBIOS_DEFINE_FIELD_STRING(2, "Product", Product),
    SMBIOS_DEFINE_FIELD_STRING(2, "Version", Version),
    SMBIOS_DEFINE_FIELD_STRING(2, "Serial Number", SerialNumber),
    SMBIOS_DEFINE_FIELD_STRING(2, "Asset Tag", AssetTag),
    SMBIOS_DEFINE_FIELD_UINT(2, "Feature Flags", FeatureFlags.Value),
    SMBIOS_DEFINE_FIELD_BIT("The board is a hosting board (for example, a motherboard)", 0),
    SMBIOS_DEFINE_FIELD_BIT("The board requires at least one daughter board or auxiliary card to function properly", 1),
    SMBIOS_DEFINE_FIELD_BIT("The board is removable", 2),
    SMBIOS_DEFINE_FIELD_BIT("The board is replaceable", 3),
    SMBIOS_DEFINE_FIELD_BIT("The board is s hot swappable", 4),
    SMBIOS_DEFINE_BIT_FIELD("Reserved for future definition by this specification", 5, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_STRING(2, "Location in Chassis", LocationInChassis),
    SMBIOS_DEFINE_FIELD_UINT(2, "Chassis Handle", ChassisHandle),
    SMBIOS_DEFINE_FIELD_ENUM(2, "Board Type", BoardType, SmbiosBaseboardTypeEnum),
    SMBIOS_DEFINE_FIELD_UINT(2, "Number of Contained Object Handles", NumberOfContainedObjectHandles),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType3FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(3, "", Manufacturer),
    SMBIOS_DEFINE_FIELD_UINT(3, "Type;", Type.Value),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_TYPE_*", 0, 7, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("Chassis lock is present", 7),
    SMBIOS_DEFINE_FIELD_UINT(3, "", Version),
    SMBIOS_DEFINE_FIELD_UINT(3, "", SerialNumber),
    SMBIOS_DEFINE_FIELD_UINT(3, "", AssetTagNumber),
    SMBIOS_DEFINE_FIELD_UINT(3, "SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_STATE_*", BootUpState),
    SMBIOS_DEFINE_FIELD_UINT(3, "SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_STATE_*", PowerSupplyState),
    SMBIOS_DEFINE_FIELD_UINT(3, "SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_STATE_*", ThermalState),
    SMBIOS_DEFINE_FIELD_UINT(3, "SMBIOS_SYSTEM_ENCLOSURE_OR_CHASSIS_SECURITY_STATE_*", SecurityStatus),
    SMBIOS_DEFINE_FIELD_UINT(3, "", OEMDefined),
    SMBIOS_DEFINE_FIELD_UINT(3, "", Height),
    SMBIOS_DEFINE_FIELD_UINT(3, "", NumberOfPowerCords),
    SMBIOS_DEFINE_FIELD_UINT(3, "", ContainedElementCount),
    SMBIOS_DEFINE_FIELD_UINT(3, "", ContainedElementRecordLength),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType4FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(4, "", SocketDesignation),
    SMBIOS_DEFINE_FIELD_UINT(4, "SMBIOS_PROCESSOR_TYPE_*", Type),
    SMBIOS_DEFINE_FIELD_UINT(4, "SMBIOS_PROCESSOR_FAMILY_*", Family),
    SMBIOS_DEFINE_FIELD_UINT(4, "", Manufacturer),
    SMBIOS_DEFINE_FIELD_UINT(4, "", ID),
    SMBIOS_DEFINE_FIELD_UINT(4, "", Version),
    SMBIOS_DEFINE_FIELD_UINT(4, "Deprecated from version 3.8.0", Voltage.Value),
    SMBIOS_DEFINE_FIELD_BIT("5V", 0),
    SMBIOS_DEFINE_FIELD_BIT("3.3V", 1),
    SMBIOS_DEFINE_FIELD_BIT("2.9V", 2),
    SMBIOS_DEFINE_FIELD_BIT("Reserved, must be zero", 3),
    SMBIOS_DEFINE_BIT_FIELD("Reserved, must be zero", 4, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("be 0", 7),
    SMBIOS_DEFINE_BIT_FIELD("voltage times 10", 0, 7, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("be 1", 7),
    SMBIOS_DEFINE_FIELD_UINT(4, "", ExternalClock),
    SMBIOS_DEFINE_FIELD_UINT(4, "", MaxSpeed),
    SMBIOS_DEFINE_FIELD_UINT(4, "", CurrentSpeed),
    SMBIOS_DEFINE_FIELD_UINT(4, "Status;", Status.Value),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_PROCESSOR_CPU_STATUS_*", 0, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Reserved, must be zero", 3, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("CPU Socket Populated", 6),
    SMBIOS_DEFINE_FIELD_BIT("Reserved, must be zero", 7),
    SMBIOS_DEFINE_FIELD_UINT(4, "SMBIOS_PROCESSOR_UPGRADE_*", Upgrade),
    SMBIOS_DEFINE_FIELD_UINT(4, "", L1CacheHandle),
    SMBIOS_DEFINE_FIELD_UINT(4, "", L2CacheHandle),
    SMBIOS_DEFINE_FIELD_UINT(4, "", L3CacheHandle),
    SMBIOS_DEFINE_FIELD_UINT(4, "", SerialNumber),
    SMBIOS_DEFINE_FIELD_UINT(4, "", AssetTag),
    SMBIOS_DEFINE_FIELD_UINT(4, "", PartNumber),
    SMBIOS_DEFINE_FIELD_UINT(4, "", CoreCount),
    SMBIOS_DEFINE_FIELD_UINT(4, "", CoreEnabled),
    SMBIOS_DEFINE_FIELD_UINT(4, "", ThreadCount),
    SMBIOS_DEFINE_FIELD_UINT(4, "Characteristics;", Characteristics.Value),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 0),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 1),
    SMBIOS_DEFINE_FIELD_BIT("64-bit Capable", 2),
    SMBIOS_DEFINE_FIELD_BIT("Multi-Core", 3),
    SMBIOS_DEFINE_FIELD_BIT("Hardware Thread", 4),
    SMBIOS_DEFINE_FIELD_BIT("Execute Protection", 5),
    SMBIOS_DEFINE_FIELD_BIT("Enhanced Virtualization", 6),
    SMBIOS_DEFINE_FIELD_BIT("Power/Performance Control", 7),
    SMBIOS_DEFINE_FIELD_BIT("128-bit Capable", 8),
    SMBIOS_DEFINE_FIELD_BIT("Arm64 SoC ID", 9),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 10, 6, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(4, "SMBIOS_PROCESSOR_FAMILY_2_*", Family2),
    SMBIOS_DEFINE_FIELD_UINT(4, "", CoreCount2),
    SMBIOS_DEFINE_FIELD_UINT(4, "", CoreEnabled2),
    SMBIOS_DEFINE_FIELD_UINT(4, "", ThreadCount2),
    SMBIOS_DEFINE_FIELD_UINT(4, "", ThreadEnabled),
    SMBIOS_DEFINE_FIELD_UINT(4, "", SocketType),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType5FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(5, "SMBIOS_MEMORY_CONTROLLER_ERROR_DETECTING_METHOD_*", ErrorDetectingMethod),
    SMBIOS_DEFINE_FIELD_UINT(5, "ErrorCorrectingCapability;", ErrorCorrectingCapability.Value),
    SMBIOS_DEFINE_FIELD_BIT("Other", 2),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 3),
    SMBIOS_DEFINE_FIELD_BIT("None", 4),
    SMBIOS_DEFINE_FIELD_BIT("Single-Bit Error Correcting", 5),
    SMBIOS_DEFINE_FIELD_BIT("Double-Bit Error Correcting", 6),
    SMBIOS_DEFINE_FIELD_BIT("Error Scrubbing", 7),
    SMBIOS_DEFINE_FIELD_UINT(5, "SMBIOS_MEMORY_CONTROLLER_INTERLEAVE_*", SupportedInterleave),
    SMBIOS_DEFINE_FIELD_UINT(5, "SMBIOS_MEMORY_CONTROLLER_INTERLEAVE_*", CurrentInterleave),
    SMBIOS_DEFINE_FIELD_UINT(5, "", MaximumMemoryModuleSize),
    SMBIOS_DEFINE_FIELD_UINT(5, "SupportedSpeeds;", SupportedSpeeds.Value),
    SMBIOS_DEFINE_FIELD_BIT("Other", 0),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 1),
    SMBIOS_DEFINE_FIELD_BIT("70ns", 2),
    SMBIOS_DEFINE_FIELD_BIT("60ns", 3),
    SMBIOS_DEFINE_FIELD_BIT("50ns", 4),
    SMBIOS_DEFINE_BIT_FIELD("Reserved, must be zero", 5, 11, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(5, "MemoryModuleVoltage;", MemoryModuleVoltage.Value),
    SMBIOS_DEFINE_FIELD_BIT("5V", 0),
    SMBIOS_DEFINE_FIELD_BIT("3.3V", 1),
    SMBIOS_DEFINE_FIELD_BIT("2.9V", 2),
    SMBIOS_DEFINE_BIT_FIELD("Reserved, must be zero", 3, 5, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(5, "", NumberOfAssociatedMemorySlots),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType6FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(6, "", SocketDesignation),
    SMBIOS_DEFINE_FIELD_UINT(6, "", BankConnections),
    SMBIOS_DEFINE_FIELD_UINT(6, "", CurrentSpeed),
    SMBIOS_DEFINE_FIELD_UINT(6, "ErrorStatus;", ErrorStatus.Value),
    SMBIOS_DEFINE_FIELD_BIT("Uncorrectable errors received for the module", 0),
    SMBIOS_DEFINE_FIELD_BIT("Correctable errors received for the module", 1),
    SMBIOS_DEFINE_FIELD_BIT("Error Status information should be obtained from the event log", 2),
    SMBIOS_DEFINE_BIT_FIELD("Reserved, set to 0", 3, 5, SmbiosDataTypeUInt),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType7FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(7, "", SocketDesignation),
    SMBIOS_DEFINE_FIELD_UINT(7, "Configuration;", Configuration.Value),
    SMBIOS_DEFINE_BIT_FIELD("1 through 8", 0, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("1b – Socketed, 0b – Not Socketed", 3),
    SMBIOS_DEFINE_FIELD_BIT("Reserved, must be zero", 4),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_CACHE_LOCATION_*", 5, 2, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("1b – Enabled, 0b – Disabled (at boot time)", 7),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_CACHE_OPERATIONAL_MODE_*", 8, 2, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Reserved, must be zero", 10, 6, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(7, "In nanoseconds, the value is 0 if the speed is unknown", CacheSpeed),
    SMBIOS_DEFINE_FIELD_UINT(7, "SMBIOS_CACHE_ERROR_CORRECTION_TYPE_*", ErrorCorrectionType),
    SMBIOS_DEFINE_FIELD_UINT(7, "SMBIOS_CACHE_SYSTEM_CACHE_TYPE_*", SystemCacheType),
    SMBIOS_DEFINE_FIELD_UINT(7, "SMBIOS_CACHE_ASSOCIATIVITY_*", Associativity),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType8FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(8, "", InternalReferenceDesignator),
    SMBIOS_DEFINE_FIELD_UINT(8, "SMBIOS_PORT_CONNECTOR_TYPE_*", InternalConnectorType),
    SMBIOS_DEFINE_FIELD_UINT(8, "", ExternalReferenceDesignator),
    SMBIOS_DEFINE_FIELD_UINT(8, "SMBIOS_PORT_CONNECTOR_TYPE_*", ExternalConnectorType),
    SMBIOS_DEFINE_FIELD_UINT(8, "SMBIOS_PORT_CONNECTOR_PORT_TYPE_*", PortType),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType9FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(9, "", Designation),
    SMBIOS_DEFINE_FIELD_UINT(9, "SMBIOS_SYSTEM_SLOTS_TYPE_*", Type),
    SMBIOS_DEFINE_FIELD_UINT(9, "SMBIOS_SYSTEM_SLOTS_DATA_BUS_WIDTH_*", DataBusWidth),
    SMBIOS_DEFINE_FIELD_UINT(9, "SMBIOS_SYSTEM_SLOTS_CURRENT_USAGE_*", CurrentUsage),
    SMBIOS_DEFINE_FIELD_UINT(9, "SMBIOS_SYSTEM_SLOTS_LENGTH_*", Length),
    SMBIOS_DEFINE_FIELD_UINT(9, "", ID),
    SMBIOS_DEFINE_FIELD_UINT(9, "Characteristics1;", Characteristics1.Value),
    SMBIOS_DEFINE_FIELD_BIT("unknown", 0),
    SMBIOS_DEFINE_FIELD_BIT("5.0 volts", 1),
    SMBIOS_DEFINE_FIELD_BIT("3.3 volts", 2),
    SMBIOS_DEFINE_FIELD_BIT("opening is shared with another slot", 3),
    SMBIOS_DEFINE_FIELD_BIT("Card slot supports PC Card-16", 4),
    SMBIOS_DEFINE_FIELD_BIT("Card slot supports CardBus", 5),
    SMBIOS_DEFINE_FIELD_BIT("Card slot supports Zoom Video", 6),
    SMBIOS_DEFINE_FIELD_BIT("Card slot supports Modem Ring Resume", 7),
    SMBIOS_DEFINE_FIELD_UINT(9, "Characteristics2;", Characteristics2.Value),
    SMBIOS_DEFINE_FIELD_BIT("slot supports Power Management Event (PME#) signal", 0),
    SMBIOS_DEFINE_FIELD_BIT("supports hot-plug devices", 1),
    SMBIOS_DEFINE_FIELD_BIT("slot supports SMBus signal", 2),
    SMBIOS_DEFINE_FIELD_BIT("slot supports bifurcation", 3),
    SMBIOS_DEFINE_FIELD_BIT("supports async/surprise removal", 4),
    SMBIOS_DEFINE_FIELD_BIT("slot, CXL 1.0 capable", 5),
    SMBIOS_DEFINE_FIELD_BIT("slot, CXL 2.0 capable", 6),
    SMBIOS_DEFINE_FIELD_BIT("slot, CXL 3.0 capable", 7),
    SMBIOS_DEFINE_FIELD_UINT(9, "", SegmentGroupNumber),
    SMBIOS_DEFINE_FIELD_UINT(9, "", BusNumber),
    SMBIOS_DEFINE_FIELD_UINT(9, "DeviceFunctionNumber;", DeviceFunctionNumber.Value),
    SMBIOS_DEFINE_BIT_FIELD("Function number", 0, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Device number", 3, 5, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(9, "", BaseDataBusWidth),
    SMBIOS_DEFINE_FIELD_UINT(9, "", PeerGroupingCount),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType10FieldInfo[] = {
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType11FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(11, "", Count),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType12FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(12, "", Count),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType13FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(13, "", InstallableLanguages),
    SMBIOS_DEFINE_FIELD_UINT(13, "Flags;", Flags.Value),
    SMBIOS_DEFINE_FIELD_BIT("Use the abbreviated format", 0),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 1, 7, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(13, "", Reserved0),
    SMBIOS_DEFINE_FIELD_UINT(13, "", Reserved[15]),
    SMBIOS_DEFINE_FIELD_UINT(13, "", CurrentLanguage),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType14FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(14, "", GroupName),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType15FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(15, "", AreaLength),
    SMBIOS_DEFINE_FIELD_UINT(15, "", HeaderStartOffset),
    SMBIOS_DEFINE_FIELD_UINT(15, "", DataStartOffset),
    SMBIOS_DEFINE_FIELD_UINT(15, "SMBIOS_SYSTEM_EVENT_LOG_ACCESSMETHOD_*", AccessMethod),
    SMBIOS_DEFINE_FIELD_UINT(15, "Status;", Status.Value),
    SMBIOS_DEFINE_FIELD_BIT("Log area valid", 0),
    SMBIOS_DEFINE_FIELD_BIT("Log area full", 1),
    SMBIOS_DEFINE_BIT_FIELD("Reserved, set to 0", 2, 6, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(15, "", ChangeToken),
    SMBIOS_DEFINE_FIELD_UINT(15, "", IndexAddr),
    SMBIOS_DEFINE_FIELD_UINT(15, "", DataAddr),
    SMBIOS_DEFINE_FIELD_UINT(15, "", PhysicalAddr32),
    SMBIOS_DEFINE_FIELD_UINT(15, "", GPNVHandle),
    SMBIOS_DEFINE_FIELD_UINT(15, "SMBIOS_SYSTEM_EVENT_LOG_HEADERFORMAT_*", HeaderFormat),
    SMBIOS_DEFINE_FIELD_UINT(15, "", NumberOfSupportedTypeDescriptors),
    SMBIOS_DEFINE_FIELD_UINT(15, "Currently hard-coded as 2", LengthOfTypeDescriptor),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType16FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(16, "SMBIOS_PHYSICAL_MEMORY_ARRAY_LOCATION_*", Location),
    SMBIOS_DEFINE_FIELD_UINT(16, "SMBIOS_PHYSICAL_MEMORY_ARRAY_USE_*", Use),
    SMBIOS_DEFINE_FIELD_UINT(16, "SMBIOS_PHYSICAL_MEMORY_ARRAY_ERROR_CORRECTION_TYPE_*", ErrorCorrection),
    SMBIOS_DEFINE_FIELD_UINT(16, "", MaximumCapacity),
    SMBIOS_DEFINE_FIELD_UINT(16, "", ErrorInformationHandle),
    SMBIOS_DEFINE_FIELD_UINT(16, "", NumberOfMemoryDevices),
    SMBIOS_DEFINE_FIELD_UINT(16, "", ExtendedMaximumCapacity),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType17FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(17, "", PhysicalMemoryArrayHandle),
    SMBIOS_DEFINE_FIELD_UINT(17, "", ErrorInformationHandle),
    SMBIOS_DEFINE_FIELD_UINT(17, "", TotalWidth),
    SMBIOS_DEFINE_FIELD_UINT(17, "", DataWidth),
    SMBIOS_DEFINE_FIELD_UINT(17, "Size;", Size.Value),
    SMBIOS_DEFINE_BIT_FIELD("", 0, 15, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("= MB, 1 = KB", 15),
    SMBIOS_DEFINE_FIELD_UINT(17, "SMBIOS_MEMORY_DEVICE_FORM_FACTOR_*", FormFactor),
    SMBIOS_DEFINE_FIELD_UINT(17, "", DeviceSet),
    SMBIOS_DEFINE_FIELD_UINT(17, "", DeviceLocator),
    SMBIOS_DEFINE_FIELD_UINT(17, "", BankLocator),
    SMBIOS_DEFINE_FIELD_UINT(17, "SMBIOS_MEMORY_DEVICE_TYPE_*", Type),
    SMBIOS_DEFINE_FIELD_UINT(17, "TypeDetail;", TypeDetail.Value),
    SMBIOS_DEFINE_FIELD_BIT("Reserved, set to 0", 0),
    SMBIOS_DEFINE_FIELD_BIT("Other", 1),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 2),
    SMBIOS_DEFINE_FIELD_BIT("Fast-paged", 3),
    SMBIOS_DEFINE_FIELD_BIT("Static column", 4),
    SMBIOS_DEFINE_FIELD_BIT("Pseudo-static", 5),
    SMBIOS_DEFINE_FIELD_BIT("RAMBUS", 6),
    SMBIOS_DEFINE_FIELD_BIT("Synchronous", 7),
    SMBIOS_DEFINE_FIELD_BIT("CMOS", 8),
    SMBIOS_DEFINE_FIELD_BIT("EDO", 9),
    SMBIOS_DEFINE_FIELD_BIT("Window DRAM", 10),
    SMBIOS_DEFINE_FIELD_BIT("Cache DRAM", 11),
    SMBIOS_DEFINE_FIELD_BIT("Non-volatile", 12),
    SMBIOS_DEFINE_FIELD_BIT("Registered (Buffered)", 13),
    SMBIOS_DEFINE_FIELD_BIT("Unbuffered (Unregistered)", 14),
    SMBIOS_DEFINE_FIELD_BIT("LRDIMM", 15),
    SMBIOS_DEFINE_FIELD_UINT(17, "", Speed),
    SMBIOS_DEFINE_FIELD_UINT(17, "", Manufacturer),
    SMBIOS_DEFINE_FIELD_UINT(17, "", SerialNumber),
    SMBIOS_DEFINE_FIELD_UINT(17, "", AssetTag),
    SMBIOS_DEFINE_FIELD_UINT(17, "", PartNumber),
    SMBIOS_DEFINE_FIELD_UINT(17, "Attributes;", Attributes.Value),
    SMBIOS_DEFINE_BIT_FIELD("0 for unknown rank information", 0, 4, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 4, 4, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(17, "ExtendedSize;", ExtendedSize.Value),
    SMBIOS_DEFINE_BIT_FIELD("Size in MB", 0, 31, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 31),
    SMBIOS_DEFINE_FIELD_UINT(17, "", ConfiguredMemorySpeed),
    SMBIOS_DEFINE_FIELD_UINT(17, "", MinimumVoltage),
    SMBIOS_DEFINE_FIELD_UINT(17, "", MaximumVoltage),
    SMBIOS_DEFINE_FIELD_UINT(17, "", ConfiguredVoltage),
    SMBIOS_DEFINE_FIELD_UINT(17, "SMBIOS_MEMORY_DEVICE_TECHNOLOGY_*", Technology),
    SMBIOS_DEFINE_FIELD_UINT(17, "OperatingModeCapability;", OperatingModeCapability.Value),
    SMBIOS_DEFINE_FIELD_BIT("Reserved, set to 0", 0),
    SMBIOS_DEFINE_FIELD_BIT("Other", 1),
    SMBIOS_DEFINE_FIELD_BIT("Unknown", 2),
    SMBIOS_DEFINE_FIELD_BIT("Volatile memory", 3),
    SMBIOS_DEFINE_FIELD_BIT("Byte-accessible persistent memory", 4),
    SMBIOS_DEFINE_FIELD_BIT("Block-accessible persistent memory", 5),
    SMBIOS_DEFINE_BIT_FIELD("Reserved, set to 0", 6, 10, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(17, "", FirmwareVersion),
    SMBIOS_DEFINE_FIELD_UINT(17, "", ModuleManufacturerID),
    SMBIOS_DEFINE_FIELD_UINT(17, "", ModuleProductID),
    SMBIOS_DEFINE_FIELD_UINT(17, "", SubsystemControllerManufacturerID),
    SMBIOS_DEFINE_FIELD_UINT(17, "", SubsystemControllerProductID),
    SMBIOS_DEFINE_FIELD_UINT(17, "", NonVolatileSize),
    SMBIOS_DEFINE_FIELD_UINT(17, "", VolatileSize),
    SMBIOS_DEFINE_FIELD_UINT(17, "", CacheSize),
    SMBIOS_DEFINE_FIELD_UINT(17, "", LogicalSize),
    SMBIOS_DEFINE_FIELD_UINT(17, "", ExtendedSpeed),
    SMBIOS_DEFINE_FIELD_UINT(17, "", ExtendedConfiguredSpeed),
    SMBIOS_DEFINE_FIELD_UINT(17, "", PMIC0ManufacturerID),
    SMBIOS_DEFINE_FIELD_UINT(17, "", PMIC0RevisionNumber),
    SMBIOS_DEFINE_FIELD_UINT(17, "", RCDManufacturerID),
    SMBIOS_DEFINE_FIELD_UINT(17, "", RCDRevisionNumber),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType18FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(18, "SMBIOS_MEMORY_ERROR_TYPE_*", Type),
    SMBIOS_DEFINE_FIELD_UINT(18, "SMBIOS_MEMORY_ERROR_GRANULARITY_*", Granularity),
    SMBIOS_DEFINE_FIELD_UINT(18, "SMBIOS_MEMORY_ERROR_OPERATION_*", Operation),
    SMBIOS_DEFINE_FIELD_UINT(18, "", VendorSyndrome),
    SMBIOS_DEFINE_FIELD_UINT(18, "", MemoryArrayErrorAddress),
    SMBIOS_DEFINE_FIELD_UINT(18, "", DeviceErrorAddress),
    SMBIOS_DEFINE_FIELD_UINT(18, "", Resolution),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType19FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(19, "", StartingAddress),
    SMBIOS_DEFINE_FIELD_UINT(19, "", EndingAddress),
    SMBIOS_DEFINE_FIELD_UINT(19, "", MemoryArrayHandle),
    SMBIOS_DEFINE_FIELD_UINT(19, "", PartitionWidth),
    SMBIOS_DEFINE_FIELD_UINT(19, "", ExtendedStartingAddress),
    SMBIOS_DEFINE_FIELD_UINT(19, "", ExtendedEndingAddress),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType20FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(20, "", StartingAddress),
    SMBIOS_DEFINE_FIELD_UINT(20, "", EndingAddress),
    SMBIOS_DEFINE_FIELD_UINT(20, "", MemoryDeviceHandle),
    SMBIOS_DEFINE_FIELD_UINT(20, "", MemoryArrayMappedAddressHandle),
    SMBIOS_DEFINE_FIELD_UINT(20, "", PartitionRowPosition),
    SMBIOS_DEFINE_FIELD_UINT(20, "", InterleavePosition),
    SMBIOS_DEFINE_FIELD_UINT(20, "", InterleavedDataDepth),
    SMBIOS_DEFINE_FIELD_UINT(20, "", ExtendedStartingAddress),
    SMBIOS_DEFINE_FIELD_UINT(20, "", ExtendedEndingAddress),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType21FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(21, "SMBIOS_BUILTIN_POINTING_DEVICE_TYPE_*", Type),
    SMBIOS_DEFINE_FIELD_UINT(21, "SMBIOS_BUILTIN_POINTING_DEVICE_INTERFACE_*", Interface),
    SMBIOS_DEFINE_FIELD_UINT(21, "", NumberOfButtons),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType22FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(22, "", Location),
    SMBIOS_DEFINE_FIELD_UINT(22, "", Manufacturer),
    SMBIOS_DEFINE_FIELD_UINT(22, "", ManufactureDate),
    SMBIOS_DEFINE_FIELD_UINT(22, "", SerialNumber),
    SMBIOS_DEFINE_FIELD_UINT(22, "", DeviceName),
    SMBIOS_DEFINE_FIELD_UINT(22, "SMBIO_PORTABLE_BATTERY_DEVICE_CHEMISTRY_*", DeviceChemistry),
    SMBIOS_DEFINE_FIELD_UINT(22, "Design capacity of the battery in milliwatt-hours, or 0 if unknown", DesignCapacity),
    SMBIOS_DEFINE_FIELD_UINT(22, "Design voltage of the battery in millivolts, or 0 if unknown", DesignVoltage),
    SMBIOS_DEFINE_FIELD_UINT(22, "", SBDSVersionNumber),
    SMBIOS_DEFINE_FIELD_UINT(22, "", MaximumError),
    SMBIOS_DEFINE_FIELD_UINT(22, "", SBDSSerialNumber),
    SMBIOS_DEFINE_FIELD_UINT(22, "SBDSManufactureDate;", SBDSManufactureDate.Value),
    SMBIOS_DEFINE_BIT_FIELD("Date, in the range 1 to 31", 0, 5, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Month, in the range 1 to 12", 5, 4, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Year, biased by 1980, in the range 0 to 127", 9, 7, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(22, "", SBDSDeviceChemistry),
    SMBIOS_DEFINE_FIELD_UINT(22, "", DesignCapacityMultiplier),
    SMBIOS_DEFINE_FIELD_UINT(22, "", OEMSpecific),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType23FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(23, "Capabilities;", Capabilities.Value),
    SMBIOS_DEFINE_FIELD_BIT("Identifies whether (1) or not (0) the system reset is enabled by the user", 0),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_SYSTEM_RESET_BOOT_OPTION_*", 1, 2, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_SYSTEM_RESET_BOOT_OPTION_*", 3, 2, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("True (1) or False (0)", 5),
    SMBIOS_DEFINE_BIT_FIELD("Reserved for future assignment by this specification, set to 00b", 6, 2, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(23, "", ResetCount),
    SMBIOS_DEFINE_FIELD_UINT(23, "", ResetLimit),
    SMBIOS_DEFINE_FIELD_UINT(23, "", TimerInterval),
    SMBIOS_DEFINE_FIELD_UINT(23, "", Timeout),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType24FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(24, "Settings;", Settings.Value),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_HARDWARE_SECURITY_SETTINGS_STATUS_*", 0, 2, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_HARDWARE_SECURITY_SETTINGS_STATUS_*", 2, 2, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_HARDWARE_SECURITY_SETTINGS_STATUS_*", 4, 2, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_HARDWARE_SECURITY_SETTINGS_STATUS_*", 6, 2, SmbiosDataTypeUInt),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType25FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(25, "01h to 12h", NextScheduledPowerOnMonth),
    SMBIOS_DEFINE_FIELD_UINT(25, "01h to 31h", NextScheduledPowerOnDayOfMonth),
    SMBIOS_DEFINE_FIELD_UINT(25, "00h to 23h", NextScheduledPowerOnHour),
    SMBIOS_DEFINE_FIELD_UINT(25, "00h to 59h", NextScheduledPowerOnMinute),
    SMBIOS_DEFINE_FIELD_UINT(25, "00h to 59h", NextScheduledPowerOnSecond),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType26FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(26, "", Description),
    SMBIOS_DEFINE_FIELD_UINT(26, "LocationAndStatus;", LocationAndStatus.Value),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_VOLTAGE_PROBE_LOCATION_*", 0, 5, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_PROBE_STATUS_*", 5, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(26, "", MaximumValue),
    SMBIOS_DEFINE_FIELD_UINT(26, "", MinimumValue),
    SMBIOS_DEFINE_FIELD_UINT(26, "", Resolution),
    SMBIOS_DEFINE_FIELD_UINT(26, "", Tolerance),
    SMBIOS_DEFINE_FIELD_UINT(26, "", Accuracy),
    SMBIOS_DEFINE_FIELD_UINT(26, "", OEMDefined),
    SMBIOS_DEFINE_FIELD_UINT(26, "Present only if the structure's length is larger than 14h", NominalValue),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType27FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(27, "", TemperatureProbeHandle),
    SMBIOS_DEFINE_FIELD_UINT(27, "DeviceTypeAndStatus;", DeviceTypeAndStatus.Value),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_COOLING_DEVICE_TYPE_*", 0, 5, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_PROBE_STATUS_*", 5, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(27, "", CoolingUnitGroup),
    SMBIOS_DEFINE_FIELD_UINT(27, "", OEMDefined),
    SMBIOS_DEFINE_FIELD_UINT(27, "", NominalSpeed),
    SMBIOS_DEFINE_FIELD_UINT(27, "", Description),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType28FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(28, "", Description),
    SMBIOS_DEFINE_FIELD_UINT(28, "LocationAndStatus;", LocationAndStatus.Value),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_TEMPERATURE_PROBE_LOCATION_*", 0, 5, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_PROBE_STATUS_*", 5, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(28, "", MaximumValue),
    SMBIOS_DEFINE_FIELD_UINT(28, "", MinimumValue),
    SMBIOS_DEFINE_FIELD_UINT(28, "", Resolution),
    SMBIOS_DEFINE_FIELD_UINT(28, "", Tolerance),
    SMBIOS_DEFINE_FIELD_UINT(28, "", Accuracy),
    SMBIOS_DEFINE_FIELD_UINT(28, "", OEMDefined),
    SMBIOS_DEFINE_FIELD_UINT(28, "", NominalValue),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType29FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(29, "", Description),
    SMBIOS_DEFINE_FIELD_UINT(29, "", LocationAndStatus),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_ELECTRICAL_CURRENT_PROBE_LOCATION_* */", 0, 5, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_PROBE_STATUS_*", 5, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(29, "", MaximumValue),
    SMBIOS_DEFINE_FIELD_UINT(29, "", MinimumValue),
    SMBIOS_DEFINE_FIELD_UINT(29, "", Resolution),
    SMBIOS_DEFINE_FIELD_UINT(29, "", Tolerance),
    SMBIOS_DEFINE_FIELD_UINT(29, "", Accuracy),
    SMBIOS_DEFINE_FIELD_UINT(29, "", OEMDefined),
    SMBIOS_DEFINE_FIELD_UINT(29, "", NominalValue),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType30FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(30, "", ManufacturerName),
    SMBIOS_DEFINE_FIELD_UINT(30, "Connections;", Connections.Value),
    SMBIOS_DEFINE_FIELD_BIT(" Inbound Connection Enabled", 0),
    SMBIOS_DEFINE_FIELD_BIT(" Outbound Connection Enabled", 1),
    SMBIOS_DEFINE_BIT_FIELD("Reserved for future definition by this specification, set to all zeros", 2, 6, SmbiosDataTypeUInt),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType32FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(32, "", Reserved[6]),
    SMBIOS_DEFINE_FIELD_UINT(32, "SMBIOS_SYSTEM_BOOT_STATUS_*", Status),
    SMBIOS_DEFINE_FIELD_UINT(32, "", AdditionalData[9]),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType33FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(33, "SMBIOS_MEMORY_ERROR_TYPE_*", Type),
    SMBIOS_DEFINE_FIELD_UINT(33, "SMBIOS_MEMORY_ERROR_GRANULARITY_*", Granularity),
    SMBIOS_DEFINE_FIELD_UINT(33, "SMBIOS_MEMORY_ERROR_OPERATION_*", Operation),
    SMBIOS_DEFINE_FIELD_UINT(33, "", VendorSyndrome),
    SMBIOS_DEFINE_FIELD_UINT(33, "", MemoryArrayErrorAddress),
    SMBIOS_DEFINE_FIELD_UINT(33, "", DeviceErrorAddress),
    SMBIOS_DEFINE_FIELD_UINT(33, "", Resolution),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType34FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(34, "", Description),
    SMBIOS_DEFINE_FIELD_UINT(34, "SMBIOS_MANAGEMENT_DEVICE_TYPE_*", Type),
    SMBIOS_DEFINE_FIELD_UINT(34, "", Address),
    SMBIOS_DEFINE_FIELD_UINT(34, "SMBIOS_MANAGEMENT_DEVICE_ADDRESS_TYPE_*", AddressType),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType35FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(35, "", Description),
    SMBIOS_DEFINE_FIELD_UINT(35, "", ManagementDeviceHandle),
    SMBIOS_DEFINE_FIELD_UINT(35, "", ComponentHandle),
    SMBIOS_DEFINE_FIELD_UINT(35, "", ThresholdHandle),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType36FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(36, "", LowerThresholdNonCritical),
    SMBIOS_DEFINE_FIELD_UINT(36, "", UpperThresholdNonCritical),
    SMBIOS_DEFINE_FIELD_UINT(36, "", LowerThresholdCritical),
    SMBIOS_DEFINE_FIELD_UINT(36, "", UpperThresholdCritical),
    SMBIOS_DEFINE_FIELD_UINT(36, "", LowerThresholdNonRecoverable),
    SMBIOS_DEFINE_FIELD_UINT(36, "", UpperThresholdNonRecoverable),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType37FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(37, "SMBIOS_MEMORY_CHANNEL_TYPE_*", Type),
    SMBIOS_DEFINE_FIELD_UINT(37, "", MaximumLoad),
    SMBIOS_DEFINE_FIELD_UINT(37, "", MemoryDeviceCount),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType38FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(38, "SMBIOS_IPMI_DEVICE_INTERFACE_TYPE_*", Type),
    SMBIOS_DEFINE_FIELD_UINT(38, "SpecificationRevision;", SpecificationRevision.Value),
    SMBIOS_DEFINE_BIT_FIELD("Least significant bits", 0, 4, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Most significant digit", 4, 4, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(38, "", I2CTargetAddress),
    SMBIOS_DEFINE_FIELD_UINT(38, "", NVStorageDeviceAddress),
    SMBIOS_DEFINE_FIELD_UINT(38, "BaseAddress;", BaseAddress.Value),
    SMBIOS_DEFINE_FIELD_BIT("1 The address is in I/O space, or 0 the address is memory-mapped", 0),
    SMBIOS_DEFINE_BIT_FIELD("Address", 1, 63, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(38, "BaseAddressInfo;", BaseAddressInfo.Value),
    SMBIOS_DEFINE_FIELD_BIT("1 = level, 0 = edge", 0),
    SMBIOS_DEFINE_FIELD_BIT("1 = active high, 0 = active low", 1),
    SMBIOS_DEFINE_FIELD_BIT("Reserved. Return as 0b", 2),
    SMBIOS_DEFINE_FIELD_BIT("1 = specified, 0 = not specified", 3),
    SMBIOS_DEFINE_FIELD_BIT("LS-bit for addresses", 4),
    SMBIOS_DEFINE_FIELD_BIT("Reserved. Return as 0b", 5),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_IPMI_DEVICE_BASEADDRESS_REGISTER_SPACING_*", 6, 2, SmbiosDataTypeUInt),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType39FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(39, "", PowerUnitGroup),
    SMBIOS_DEFINE_FIELD_UINT(39, "", Location),
    SMBIOS_DEFINE_FIELD_UINT(39, "", DeviceName),
    SMBIOS_DEFINE_FIELD_UINT(39, "", Manufacturer),
    SMBIOS_DEFINE_FIELD_UINT(39, "", SerialNumber),
    SMBIOS_DEFINE_FIELD_UINT(39, "", AssetTagNumber),
    SMBIOS_DEFINE_FIELD_UINT(39, "", ModelPartNumber),
    SMBIOS_DEFINE_FIELD_UINT(39, "", RevisionLevel),
    SMBIOS_DEFINE_FIELD_UINT(39, "", MaxPowerCapacity),
    SMBIOS_DEFINE_FIELD_UINT(39, "Characteristics;", Characteristics.Value),
    SMBIOS_DEFINE_FIELD_BIT("Power supply is hot-replaceable", 0),
    SMBIOS_DEFINE_FIELD_BIT("Power supply is present", 1),
    SMBIOS_DEFINE_FIELD_BIT("Power supply is unplugged from the wall", 2),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_SYSTEM_POWER_SUPPLY_INPUT_VOLTAGE_RANGE_SWITCHING_*", 3, 4, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_SYSTEM_POWER_SUPPLY_STATUS_*", 7, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_SYSTEM_POWER_SUPPLY_TYPE_*", 10, 4, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Reserved, set to 00b", 14, 2, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(39, "", InputVoltageProbeHandle),
    SMBIOS_DEFINE_FIELD_UINT(39, "", CoolingDeviceHandle),
    SMBIOS_DEFINE_FIELD_UINT(39, "", InputCurrentProbeHandle),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType40FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(40, "", Count),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType41FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(41, "", ReferenceDesignation),
    SMBIOS_DEFINE_FIELD_UINT(41, "Type;", Type.Value),
    SMBIOS_DEFINE_BIT_FIELD("SMBIOS_ONBOARD_DEVICES_EXTENDED_TYPE_*", 0, 7, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_BIT("1 – Device Enabled, 0 – Device Disabled", 7),
    SMBIOS_DEFINE_FIELD_UINT(41, "", TypeInstance),
    SMBIOS_DEFINE_FIELD_UINT(41, "", SegmentGroupNumber),
    SMBIOS_DEFINE_FIELD_UINT(41, "", BusNumber),
    SMBIOS_DEFINE_FIELD_UINT(41, "DeviceFunctionNumber;", DeviceFunctionNumber.Value),
    SMBIOS_DEFINE_BIT_FIELD("Function number", 0, 3, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_BIT_FIELD("Device number", 3, 5, SmbiosDataTypeUInt),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType42FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(42, "00h–3Fh MCTP Host Interfaces, 40h Network Host Interface, F0h OEM-defined, others Reserved", Type),
    SMBIOS_DEFINE_FIELD_UINT(42, "", TypeSpecificDataLength),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType43FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(43, "", VendorID[4]),
    SMBIOS_DEFINE_FIELD_UINT(43, "", MajorSpecVersion),
    SMBIOS_DEFINE_FIELD_UINT(43, "", MinorSpecVersion),
    SMBIOS_DEFINE_FIELD_UINT(43, "", FirmwareVersion1),
    SMBIOS_DEFINE_FIELD_UINT(43, "", FirmwareVersion2),
    SMBIOS_DEFINE_FIELD_UINT(43, "", Description),
    SMBIOS_DEFINE_FIELD_UINT(43, "Characteristics;", Characteristics.Value),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 0),
    SMBIOS_DEFINE_FIELD_BIT("Reserved", 1),
    SMBIOS_DEFINE_FIELD_BIT("Characteristics are not supported", 2),
    SMBIOS_DEFINE_FIELD_BIT("Family configurable via firmware update", 3),
    SMBIOS_DEFINE_FIELD_BIT("Family configurable via platform software support", 4),
    SMBIOS_DEFINE_FIELD_BIT("Family configurable via OEM proprietary mechanism", 5),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 6, 58, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(43, "", OEMDefined),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType44FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(44, "", ReferencedHandle),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType45FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(45, "", ComponentName),
    SMBIOS_DEFINE_FIELD_UINT(45, "", Version),
    SMBIOS_DEFINE_FIELD_UINT(45, "SMBIOS_FIRMWARE_INVENTORY_VERSION_FORMAT_*, 04h–7Fh Available for future assignment by this specification, 80h-FFh Firmware Vendor/OEM-specific", VersionFormat),
    SMBIOS_DEFINE_FIELD_UINT(45, "", ID),
    SMBIOS_DEFINE_FIELD_UINT(45, "SMBIOS_FIRMWARE_INVENTORY_ID_FORMAT_*, 02h–7Fh Available for future assignment by this specification, 80h-FFh Firmware Vendor/OEM-specific", IDFormat),
    SMBIOS_DEFINE_FIELD_UINT(45, "", ReleaseDate),
    SMBIOS_DEFINE_FIELD_UINT(45, "", Manufacturer),
    SMBIOS_DEFINE_FIELD_UINT(45, "SMBIOS_FIRMWARE_INVENTORY_VERSION_FORMAT_*", LowestSupportedFirmwareVersion),
    SMBIOS_DEFINE_FIELD_UINT(45, "", ImageSize),
    SMBIOS_DEFINE_FIELD_UINT(45, "Characteristics;", Characteristics.Value),
    SMBIOS_DEFINE_FIELD_BIT("Updatable", 0),
    SMBIOS_DEFINE_FIELD_BIT("Write-Protect", 1),
    SMBIOS_DEFINE_BIT_FIELD("Reserved", 2, 14, SmbiosDataTypeUInt),
    SMBIOS_DEFINE_FIELD_UINT(45, "SMBIOS_FIRMWARE_INVENTORY_STATE_*", State),
    SMBIOS_DEFINE_FIELD_UINT(45, "", NumberOfAssociatedComponents),
};

__declspec(selectany)
SMBIOS_FIELD_TYPE_INFO SmbiosType46FieldInfo[] = {
    SMBIOS_DEFINE_FIELD_UINT(46, "SMBIOS_STRING_PROPERTY_ID_*", ID),
    SMBIOS_DEFINE_FIELD_UINT(46, "", String),
    SMBIOS_DEFINE_FIELD_UINT(46, "", ParentHandle),
};

